-- SQL Logging Session
-- Session ID: 76142961-c3e5-4417-95a1-cb738e37021f
-- Started: 2026-07-27T17:05:43.752Z
-- Description: MetadataSync push operation
-- Format: Migration-ready with Flyway schema placeholders
-- Generated by MemberJunction

-- Save MJ_BizApps_Sonar: Score Band Sets (core SP call only)
DECLARE @ID_fb854c01 UNIQUEIDENTIFIER,
@Name_fb854c01 NVARCHAR(200),
@AnchorEntityID_fb854c01 UNIQUEIDENTIFIER,
@Description_fb854c01 NVARCHAR(MAX)
SET
  @ID_fb854c01 = '82A80C88-CF9D-5386-A3C5-8ACDE3025B55'
SET
  @Name_fb854c01 = N'MoreCheese Engagement Bands'
SET
  @AnchorEntityID_fb854c01 = '7A94ADA9-7880-4FAE-97D8-DB0E934C3F5F'
SET
  @Description_fb854c01 = N'Qualitative engagement bands for the member score.' EXEC [__mj_BizAppsSonar].spCreateScoreBandSet @ID = @ID_fb854c01,
  @Name = @Name_fb854c01,
  @AnchorEntityID = @AnchorEntityID_fb854c01,
  @Description = @Description_fb854c01;

GO

-- Save MJ_BizApps_Sonar: Score Bands (core SP call only)
DECLARE @ID_fc4251d5 UNIQUEIDENTIFIER,
@BandSetID_fc4251d5 UNIQUEIDENTIFIER,
@Label_fc4251d5 NVARCHAR(60),
@MinScore_fc4251d5 DECIMAL(9, 4),
@MaxScore_fc4251d5 DECIMAL(9, 4),
@Severity_fc4251d5 INT,
@ColorHex_fc4251d5 NVARCHAR(7),
@IsTerminal_fc4251d5 BIT,
@Description_fc4251d5 NVARCHAR(MAX)
SET
  @ID_fc4251d5 = '4B51BE35-94A0-5760-AAB5-F7803EC1C22B'
SET
  @BandSetID_fc4251d5 = '82A80C88-CF9D-5386-A3C5-8ACDE3025B55'
SET
  @Label_fc4251d5 = N'At Risk'
SET
  @MinScore_fc4251d5 = 0
SET
  @MaxScore_fc4251d5 = 10
SET
  @Severity_fc4251d5 = 3
SET
  @ColorHex_fc4251d5 = N'#D9534F'
SET
  @IsTerminal_fc4251d5 = 0
SET
  @Description_fc4251d5 = N'Disengaged — renewal is in doubt without intervention.' EXEC [__mj_BizAppsSonar].spCreateScoreBand @ID = @ID_fc4251d5,
  @BandSetID = @BandSetID_fc4251d5,
  @Label = @Label_fc4251d5,
  @MinScore = @MinScore_fc4251d5,
  @MaxScore = @MaxScore_fc4251d5,
  @Severity = @Severity_fc4251d5,
  @ColorHex = @ColorHex_fc4251d5,
  @IsTerminal = @IsTerminal_fc4251d5,
  @Description = @Description_fc4251d5;

GO

-- Save MJ_BizApps_Sonar: Score Bands (core SP call only)
DECLARE @ID_eea4aec8 UNIQUEIDENTIFIER,
@BandSetID_eea4aec8 UNIQUEIDENTIFIER,
@Label_eea4aec8 NVARCHAR(60),
@MinScore_eea4aec8 DECIMAL(9, 4),
@MaxScore_eea4aec8 DECIMAL(9, 4),
@Severity_eea4aec8 INT,
@ColorHex_eea4aec8 NVARCHAR(7),
@IsTerminal_eea4aec8 BIT,
@Description_eea4aec8 NVARCHAR(MAX)
SET
  @ID_eea4aec8 = 'CD02E66D-C02F-5BC7-BC62-5DA43A65E10F'
SET
  @BandSetID_eea4aec8 = '82A80C88-CF9D-5386-A3C5-8ACDE3025B55'
SET
  @Label_eea4aec8 = N'Watch'
SET
  @MinScore_eea4aec8 = 10
SET
  @MaxScore_eea4aec8 = 20
SET
  @Severity_eea4aec8 = 2
SET
  @ColorHex_eea4aec8 = N'#F0AD4E'
SET
  @IsTerminal_eea4aec8 = 0
SET
  @Description_eea4aec8 = N'Below-average engagement — worth a touchpoint.' EXEC [__mj_BizAppsSonar].spCreateScoreBand @ID = @ID_eea4aec8,
  @BandSetID = @BandSetID_eea4aec8,
  @Label = @Label_eea4aec8,
  @MinScore = @MinScore_eea4aec8,
  @MaxScore = @MaxScore_eea4aec8,
  @Severity = @Severity_eea4aec8,
  @ColorHex = @ColorHex_eea4aec8,
  @IsTerminal = @IsTerminal_eea4aec8,
  @Description = @Description_eea4aec8;

GO

-- Save MJ_BizApps_Sonar: Score Bands (core SP call only)
DECLARE @ID_2ca6a788 UNIQUEIDENTIFIER,
@BandSetID_2ca6a788 UNIQUEIDENTIFIER,
@Label_2ca6a788 NVARCHAR(60),
@MinScore_2ca6a788 DECIMAL(9, 4),
@MaxScore_2ca6a788 DECIMAL(9, 4),
@Severity_2ca6a788 INT,
@ColorHex_2ca6a788 NVARCHAR(7),
@IsTerminal_2ca6a788 BIT,
@Description_2ca6a788 NVARCHAR(MAX)
SET
  @ID_2ca6a788 = 'ED587C74-F495-5AF6-8E7A-1F0D892AB80E'
SET
  @BandSetID_2ca6a788 = '82A80C88-CF9D-5386-A3C5-8ACDE3025B55'
SET
  @Label_2ca6a788 = N'Stable'
SET
  @MinScore_2ca6a788 = 20
SET
  @MaxScore_2ca6a788 = 35
SET
  @Severity_2ca6a788 = 1
SET
  @ColorHex_2ca6a788 = N'#5BC0DE'
SET
  @IsTerminal_2ca6a788 = 0
SET
  @Description_2ca6a788 = N'Healthy, steady participation.' EXEC [__mj_BizAppsSonar].spCreateScoreBand @ID = @ID_2ca6a788,
  @BandSetID = @BandSetID_2ca6a788,
  @Label = @Label_2ca6a788,
  @MinScore = @MinScore_2ca6a788,
  @MaxScore = @MaxScore_2ca6a788,
  @Severity = @Severity_2ca6a788,
  @ColorHex = @ColorHex_2ca6a788,
  @IsTerminal = @IsTerminal_2ca6a788,
  @Description = @Description_2ca6a788;

GO

-- Save MJ_BizApps_Sonar: Score Bands (core SP call only)
DECLARE @ID_fc8a9a9f UNIQUEIDENTIFIER,
@BandSetID_fc8a9a9f UNIQUEIDENTIFIER,
@Label_fc8a9a9f NVARCHAR(60),
@MinScore_fc8a9a9f DECIMAL(9, 4),
@MaxScore_fc8a9a9f DECIMAL(9, 4),
@Severity_fc8a9a9f INT,
@ColorHex_fc8a9a9f NVARCHAR(7),
@IsTerminal_fc8a9a9f BIT,
@Description_fc8a9a9f NVARCHAR(MAX)
SET
  @ID_fc8a9a9f = '36C432E5-EE8F-57F8-8BF6-808EC147C339'
SET
  @BandSetID_fc8a9a9f = '82A80C88-CF9D-5386-A3C5-8ACDE3025B55'
SET
  @Label_fc8a9a9f = N'Engaged'
SET
  @MinScore_fc8a9a9f = 35
SET
  @MaxScore_fc8a9a9f = 100
SET
  @Severity_fc8a9a9f = 0
SET
  @ColorHex_fc8a9a9f = N'#5CB85C'
SET
  @IsTerminal_fc8a9a9f = 0
SET
  @Description_fc8a9a9f = N'Highly engaged — advocates and volunteers live here.' EXEC [__mj_BizAppsSonar].spCreateScoreBand @ID = @ID_fc8a9a9f,
  @BandSetID = @BandSetID_fc8a9a9f,
  @Label = @Label_fc8a9a9f,
  @MinScore = @MinScore_fc8a9a9f,
  @MaxScore = @MaxScore_fc8a9a9f,
  @Severity = @Severity_fc8a9a9f,
  @ColorHex = @ColorHex_fc8a9a9f,
  @IsTerminal = @IsTerminal_fc8a9a9f,
  @Description = @Description_fc8a9a9f;

GO

-- Save MJ_BizApps_Sonar: Time Windows (core SP call only)
DECLARE @ID_7e96c47f UNIQUEIDENTIFIER,
@Name_7e96c47f NVARCHAR(120),
@WindowType_7e96c47f NVARCHAR(20),
@LengthDays_7e96c47f INT,
@LengthMonths_7e96c47f INT,
@AnchorDateField_7e96c47f NVARCHAR(200),
@OffsetDays_7e96c47f INT,
@Description_7e96c47f NVARCHAR(MAX)
SET
  @ID_7e96c47f = 'CF6F428F-7016-5898-BF94-22795E3B3F91'
SET
  @Name_7e96c47f = N'Trailing 12 Months (MoreCheese)'
SET
  @WindowType_7e96c47f = N'Rolling'
SET
  @LengthMonths_7e96c47f = 12
EXEC [__mj_BizAppsSonar].spCreateTimeWindow @ID = @ID_7e96c47f,
  @Name = @Name_7e96c47f,
  @WindowType = @WindowType_7e96c47f,
  @LengthDays = @LengthDays_7e96c47f,
  @LengthDays_Clear = 1,
  @LengthMonths = @LengthMonths_7e96c47f,
  @AnchorDateField = @AnchorDateField_7e96c47f,
  @AnchorDateField_Clear = 1,
  @OffsetDays = @OffsetDays_7e96c47f,
  @OffsetDays_Clear = 1,
  @Description = @Description_7e96c47f,
  @Description_Clear = 1;

GO

-- Save MJ_BizApps_Sonar: Time Windows (core SP call only)
DECLARE @ID_e7911cc7 UNIQUEIDENTIFIER,
@Name_e7911cc7 NVARCHAR(120),
@WindowType_e7911cc7 NVARCHAR(20),
@LengthDays_e7911cc7 INT,
@LengthMonths_e7911cc7 INT,
@AnchorDateField_e7911cc7 NVARCHAR(200),
@OffsetDays_e7911cc7 INT,
@Description_e7911cc7 NVARCHAR(MAX)
SET
  @ID_e7911cc7 = '97DF3796-A479-558E-9927-755A48D0D061'
SET
  @Name_e7911cc7 = N'Trailing 24 Months (MoreCheese)'
SET
  @WindowType_e7911cc7 = N'Rolling'
SET
  @LengthMonths_e7911cc7 = 24
EXEC [__mj_BizAppsSonar].spCreateTimeWindow @ID = @ID_e7911cc7,
  @Name = @Name_e7911cc7,
  @WindowType = @WindowType_e7911cc7,
  @LengthDays = @LengthDays_e7911cc7,
  @LengthDays_Clear = 1,
  @LengthMonths = @LengthMonths_e7911cc7,
  @AnchorDateField = @AnchorDateField_e7911cc7,
  @AnchorDateField_Clear = 1,
  @OffsetDays = @OffsetDays_e7911cc7,
  @OffsetDays_Clear = 1,
  @Description = @Description_e7911cc7,
  @Description_Clear = 1;

GO

-- Save MJ_BizApps_Sonar: Score Models (core SP call only)
DECLARE @ID_9f17c1a1 UNIQUEIDENTIFIER,
@Name_9f17c1a1 NVARCHAR(200),
@Slug_9f17c1a1 NVARCHAR(100),
@Description_9f17c1a1 NVARCHAR(MAX),
@AnchorEntityID_9f17c1a1 UNIQUEIDENTIFIER,
@Status_9f17c1a1 NVARCHAR(20),
@CurrentVersionID_9f17c1a1 UNIQUEIDENTIFIER,
@ScoreScaleMin_9f17c1a1 DECIMAL(9, 4),
@ScoreScaleMax_9f17c1a1 DECIMAL(9, 4),
@CombineStrategy_9f17c1a1 NVARCHAR(30),
@CombineExpression_9f17c1a1 NVARCHAR(MAX),
@BandSetID_9f17c1a1 UNIQUEIDENTIFIER,
@PopulationFilter_9f17c1a1 NVARCHAR(MAX),
@RecomputeMode_9f17c1a1 NVARCHAR(20),
@RecomputeCron_9f17c1a1 NVARCHAR(100),
@AsOfStrategy_9f17c1a1 NVARCHAR(20),
@IsCalibrated_9f17c1a1 BIT,
@TrendWindowDays_9f17c1a1 INT,
@OwnerUserID_9f17c1a1 UNIQUEIDENTIFIER,
@EffectiveFrom_9f17c1a1 DATETIME2,
@EffectiveTo_9f17c1a1 DATETIME2,
@Notes_9f17c1a1 NVARCHAR(MAX)
SET
  @ID_9f17c1a1 = '05C13018-27B8-53DE-9D1D-129E6E15DF1C'
SET
  @Name_9f17c1a1 = N'Member Engagement Score'
SET
  @Slug_9f17c1a1 = N'morecheese-engagement'
SET
  @Description_9f17c1a1 = N'Composite engagement score for federation members — breadth, recency, and depth of participation across events, governance, learning, advocacy, surveys, certifications, and competitions. The retention early-warning dial, computed live by Sonar.'
SET
  @AnchorEntityID_9f17c1a1 = '7A94ADA9-7880-4FAE-97D8-DB0E934C3F5F'
SET
  @Status_9f17c1a1 = N'Active'
SET
  @ScoreScaleMin_9f17c1a1 = 0
SET
  @ScoreScaleMax_9f17c1a1 = 100
SET
  @CombineStrategy_9f17c1a1 = N'WeightedSum'
SET
  @BandSetID_9f17c1a1 = '82A80C88-CF9D-5386-A3C5-8ACDE3025B55'
SET
  @RecomputeMode_9f17c1a1 = N'Scheduled'
SET
  @AsOfStrategy_9f17c1a1 = N'RunTime'
SET
  @IsCalibrated_9f17c1a1 = 0
SET
  @OwnerUserID_9f17c1a1 = 'C6309AFC-F5DE-5794-8865-FC99D5DD82F4'
SET
  @EffectiveFrom_9f17c1a1 = '2025-10-04T10:00:00.000Z' EXEC [__mj_BizAppsSonar].spCreateScoreModel @ID = @ID_9f17c1a1,
  @Name = @Name_9f17c1a1,
  @Slug = @Slug_9f17c1a1,
  @Description = @Description_9f17c1a1,
  @AnchorEntityID = @AnchorEntityID_9f17c1a1,
  @Status = @Status_9f17c1a1,
  @CurrentVersionID = @CurrentVersionID_9f17c1a1,
  @CurrentVersionID_Clear = 1,
  @ScoreScaleMin = @ScoreScaleMin_9f17c1a1,
  @ScoreScaleMax = @ScoreScaleMax_9f17c1a1,
  @CombineStrategy = @CombineStrategy_9f17c1a1,
  @CombineExpression = @CombineExpression_9f17c1a1,
  @CombineExpression_Clear = 1,
  @BandSetID = @BandSetID_9f17c1a1,
  @PopulationFilter = @PopulationFilter_9f17c1a1,
  @PopulationFilter_Clear = 1,
  @RecomputeMode = @RecomputeMode_9f17c1a1,
  @RecomputeCron = @RecomputeCron_9f17c1a1,
  @RecomputeCron_Clear = 1,
  @AsOfStrategy = @AsOfStrategy_9f17c1a1,
  @IsCalibrated = @IsCalibrated_9f17c1a1,
  @TrendWindowDays = @TrendWindowDays_9f17c1a1,
  @TrendWindowDays_Clear = 1,
  @OwnerUserID = @OwnerUserID_9f17c1a1,
  @EffectiveFrom = @EffectiveFrom_9f17c1a1,
  @EffectiveTo = @EffectiveTo_9f17c1a1,
  @EffectiveTo_Clear = 1,
  @Notes = @Notes_9f17c1a1,
  @Notes_Clear = 1;

GO

-- Save MJ_BizApps_Sonar: Score Model Versions (core SP call only)
DECLARE @ID_85a7d96b UNIQUEIDENTIFIER,
@ScoreModelID_85a7d96b UNIQUEIDENTIFIER,
@VersionNumber_85a7d96b INT,
@VersionLabel_85a7d96b NVARCHAR(50),
@ConfigSnapshotJSON_85a7d96b NVARCHAR(MAX),
@ChangeSummary_85a7d96b NVARCHAR(MAX),
@PublishedByUserID_85a7d96b UNIQUEIDENTIFIER,
@PublishedAt_85a7d96b DATETIME2,
@IsCurrent_85a7d96b BIT
SET
  @ID_85a7d96b = '9EC51FE5-B002-564E-9C7E-7B8E4954CC5B'
SET
  @ScoreModelID_85a7d96b = '05C13018-27B8-53DE-9D1D-129E6E15DF1C'
SET
  @VersionNumber_85a7d96b = 1
SET
  @VersionLabel_85a7d96b = N'v1'
SET
  @ConfigSnapshotJSON_85a7d96b = N'{"slug":"morecheese-engagement","combine":"WeightedSum","scale":[0,100],"factors":[{"slug":"morecheese-event-participation","source":"MoreCheese: Event Registrations","aggregation":"Count","weight":3},{"slug":"morecheese-committee-service","source":"Committees: Memberships","aggregation":"Count","weight":3},{"slug":"morecheese-certifications","source":"MoreCheese: Member Certifications","aggregation":"Count","weight":3},{"slug":"morecheese-learning-activity","source":"MoreCheese: Course Enrollments","aggregation":"Count","weight":2},{"slug":"morecheese-advocacy-participation","source":"MoreCheese: Advocacy Actions","aggregation":"Count","weight":2},{"slug":"morecheese-competition-entries","source":"MoreCheese: Competition Entries","aggregation":"Count","weight":2},{"slug":"morecheese-event-recency","source":"MoreCheese: Event Registrations","aggregation":"Count","weight":2},{"slug":"morecheese-survey-participation","source":"MJ_BizApps_Forms: Form Responses","aggregation":"Count","weight":1}],"bands":[{"label":"At Risk","min":0,"max":10},{"label":"Watch","min":10,"max":20},{"label":"Stable","min":20,"max":35},{"label":"Engaged","min":35,"max":100}]}'
SET
  @ChangeSummary_85a7d96b = N'Initial published configuration.'
SET
  @PublishedByUserID_85a7d96b = 'C6309AFC-F5DE-5794-8865-FC99D5DD82F4'
SET
  @PublishedAt_85a7d96b = '2025-10-24T14:00:00.000Z'
SET
  @IsCurrent_85a7d96b = 1
EXEC [__mj_BizAppsSonar].spCreateScoreModelVersion @ID = @ID_85a7d96b,
  @ScoreModelID = @ScoreModelID_85a7d96b,
  @VersionNumber = @VersionNumber_85a7d96b,
  @VersionLabel = @VersionLabel_85a7d96b,
  @ConfigSnapshotJSON = @ConfigSnapshotJSON_85a7d96b,
  @ChangeSummary = @ChangeSummary_85a7d96b,
  @PublishedByUserID = @PublishedByUserID_85a7d96b,
  @PublishedAt = @PublishedAt_85a7d96b,
  @IsCurrent = @IsCurrent_85a7d96b;

GO

-- Save MJ_BizApps_Sonar: Model Related Entities (core SP call only)
DECLARE @ID_96dcf3dd UNIQUEIDENTIFIER,
@ScoreModelID_96dcf3dd UNIQUEIDENTIFIER,
@RelatedEntityID_96dcf3dd UNIQUEIDENTIFIER,
@Alias_96dcf3dd NVARCHAR(100),
@RelationshipPath_96dcf3dd NVARCHAR(MAX),
@JoinType_96dcf3dd NVARCHAR(10),
@SourceSystemTag_96dcf3dd NVARCHAR(60),
@Description_96dcf3dd NVARCHAR(MAX)
SET
  @ID_96dcf3dd = 'F0E5F480-36AB-5E85-B8B8-7C7255837A32'
SET
  @ScoreModelID_96dcf3dd = '05C13018-27B8-53DE-9D1D-129E6E15DF1C'
SET
  @RelatedEntityID_96dcf3dd = '37C1AADD-E111-4604-AD2C-264775B1A076'
SET
  @Alias_96dcf3dd = N'registrations'
SET
  @RelationshipPath_96dcf3dd = N'[]'
SET
  @JoinType_96dcf3dd = N'Left' EXEC [__mj_BizAppsSonar].spCreateModelRelatedEntity @ID = @ID_96dcf3dd,
  @ScoreModelID = @ScoreModelID_96dcf3dd,
  @RelatedEntityID = @RelatedEntityID_96dcf3dd,
  @Alias = @Alias_96dcf3dd,
  @RelationshipPath = @RelationshipPath_96dcf3dd,
  @JoinType = @JoinType_96dcf3dd,
  @SourceSystemTag = @SourceSystemTag_96dcf3dd,
  @SourceSystemTag_Clear = 1,
  @Description = @Description_96dcf3dd,
  @Description_Clear = 1;

GO

-- Save MJ_BizApps_Sonar: Model Related Entities (core SP call only)
DECLARE @ID_cf9a0fe5 UNIQUEIDENTIFIER,
@ScoreModelID_cf9a0fe5 UNIQUEIDENTIFIER,
@RelatedEntityID_cf9a0fe5 UNIQUEIDENTIFIER,
@Alias_cf9a0fe5 NVARCHAR(100),
@RelationshipPath_cf9a0fe5 NVARCHAR(MAX),
@JoinType_cf9a0fe5 NVARCHAR(10),
@SourceSystemTag_cf9a0fe5 NVARCHAR(60),
@Description_cf9a0fe5 NVARCHAR(MAX)
SET
  @ID_cf9a0fe5 = '1513A3B7-DC66-57D2-9FC5-F364F3147205'
SET
  @ScoreModelID_cf9a0fe5 = '05C13018-27B8-53DE-9D1D-129E6E15DF1C'
SET
  @RelatedEntityID_cf9a0fe5 = 'F8FADBBE-A323-48FB-8395-3B543729F6E6'
SET
  @Alias_cf9a0fe5 = N'committees'
SET
  @RelationshipPath_cf9a0fe5 = N'[]'
SET
  @JoinType_cf9a0fe5 = N'Left' EXEC [__mj_BizAppsSonar].spCreateModelRelatedEntity @ID = @ID_cf9a0fe5,
  @ScoreModelID = @ScoreModelID_cf9a0fe5,
  @RelatedEntityID = @RelatedEntityID_cf9a0fe5,
  @Alias = @Alias_cf9a0fe5,
  @RelationshipPath = @RelationshipPath_cf9a0fe5,
  @JoinType = @JoinType_cf9a0fe5,
  @SourceSystemTag = @SourceSystemTag_cf9a0fe5,
  @SourceSystemTag_Clear = 1,
  @Description = @Description_cf9a0fe5,
  @Description_Clear = 1;

GO

-- Save MJ_BizApps_Sonar: Model Related Entities (core SP call only)
DECLARE @ID_c408358d UNIQUEIDENTIFIER,
@ScoreModelID_c408358d UNIQUEIDENTIFIER,
@RelatedEntityID_c408358d UNIQUEIDENTIFIER,
@Alias_c408358d NVARCHAR(100),
@RelationshipPath_c408358d NVARCHAR(MAX),
@JoinType_c408358d NVARCHAR(10),
@SourceSystemTag_c408358d NVARCHAR(60),
@Description_c408358d NVARCHAR(MAX)
SET
  @ID_c408358d = 'E5508983-6C7F-5379-8537-FB54E23630FE'
SET
  @ScoreModelID_c408358d = '05C13018-27B8-53DE-9D1D-129E6E15DF1C'
SET
  @RelatedEntityID_c408358d = 'F4D4BA79-C264-45C6-9A51-A00571ABCD6B'
SET
  @Alias_c408358d = N'certifications'
SET
  @RelationshipPath_c408358d = N'[]'
SET
  @JoinType_c408358d = N'Left' EXEC [__mj_BizAppsSonar].spCreateModelRelatedEntity @ID = @ID_c408358d,
  @ScoreModelID = @ScoreModelID_c408358d,
  @RelatedEntityID = @RelatedEntityID_c408358d,
  @Alias = @Alias_c408358d,
  @RelationshipPath = @RelationshipPath_c408358d,
  @JoinType = @JoinType_c408358d,
  @SourceSystemTag = @SourceSystemTag_c408358d,
  @SourceSystemTag_Clear = 1,
  @Description = @Description_c408358d,
  @Description_Clear = 1;

GO

-- Save MJ_BizApps_Sonar: Model Related Entities (core SP call only)
DECLARE @ID_fa1e5be7 UNIQUEIDENTIFIER,
@ScoreModelID_fa1e5be7 UNIQUEIDENTIFIER,
@RelatedEntityID_fa1e5be7 UNIQUEIDENTIFIER,
@Alias_fa1e5be7 NVARCHAR(100),
@RelationshipPath_fa1e5be7 NVARCHAR(MAX),
@JoinType_fa1e5be7 NVARCHAR(10),
@SourceSystemTag_fa1e5be7 NVARCHAR(60),
@Description_fa1e5be7 NVARCHAR(MAX)
SET
  @ID_fa1e5be7 = '8032E327-83FA-5297-A791-EE91AD2CABC5'
SET
  @ScoreModelID_fa1e5be7 = '05C13018-27B8-53DE-9D1D-129E6E15DF1C'
SET
  @RelatedEntityID_fa1e5be7 = 'FE8BF319-06BC-4E03-A22A-7864DB37579F'
SET
  @Alias_fa1e5be7 = N'enrollments'
SET
  @RelationshipPath_fa1e5be7 = N'[]'
SET
  @JoinType_fa1e5be7 = N'Left' EXEC [__mj_BizAppsSonar].spCreateModelRelatedEntity @ID = @ID_fa1e5be7,
  @ScoreModelID = @ScoreModelID_fa1e5be7,
  @RelatedEntityID = @RelatedEntityID_fa1e5be7,
  @Alias = @Alias_fa1e5be7,
  @RelationshipPath = @RelationshipPath_fa1e5be7,
  @JoinType = @JoinType_fa1e5be7,
  @SourceSystemTag = @SourceSystemTag_fa1e5be7,
  @SourceSystemTag_Clear = 1,
  @Description = @Description_fa1e5be7,
  @Description_Clear = 1;

GO

-- Save MJ_BizApps_Sonar: Model Related Entities (core SP call only)
DECLARE @ID_7b50db97 UNIQUEIDENTIFIER,
@ScoreModelID_7b50db97 UNIQUEIDENTIFIER,
@RelatedEntityID_7b50db97 UNIQUEIDENTIFIER,
@Alias_7b50db97 NVARCHAR(100),
@RelationshipPath_7b50db97 NVARCHAR(MAX),
@JoinType_7b50db97 NVARCHAR(10),
@SourceSystemTag_7b50db97 NVARCHAR(60),
@Description_7b50db97 NVARCHAR(MAX)
SET
  @ID_7b50db97 = '123C5F43-B18B-5C63-AF54-4D6E3015635F'
SET
  @ScoreModelID_7b50db97 = '05C13018-27B8-53DE-9D1D-129E6E15DF1C'
SET
  @RelatedEntityID_7b50db97 = '318E1216-842B-4EF7-8AD5-FCC4FC83E16E'
SET
  @Alias_7b50db97 = N'advocacy'
SET
  @RelationshipPath_7b50db97 = N'[]'
SET
  @JoinType_7b50db97 = N'Left' EXEC [__mj_BizAppsSonar].spCreateModelRelatedEntity @ID = @ID_7b50db97,
  @ScoreModelID = @ScoreModelID_7b50db97,
  @RelatedEntityID = @RelatedEntityID_7b50db97,
  @Alias = @Alias_7b50db97,
  @RelationshipPath = @RelationshipPath_7b50db97,
  @JoinType = @JoinType_7b50db97,
  @SourceSystemTag = @SourceSystemTag_7b50db97,
  @SourceSystemTag_Clear = 1,
  @Description = @Description_7b50db97,
  @Description_Clear = 1;

GO

-- Save MJ_BizApps_Sonar: Model Related Entities (core SP call only)
DECLARE @ID_7da1c4d9 UNIQUEIDENTIFIER,
@ScoreModelID_7da1c4d9 UNIQUEIDENTIFIER,
@RelatedEntityID_7da1c4d9 UNIQUEIDENTIFIER,
@Alias_7da1c4d9 NVARCHAR(100),
@RelationshipPath_7da1c4d9 NVARCHAR(MAX),
@JoinType_7da1c4d9 NVARCHAR(10),
@SourceSystemTag_7da1c4d9 NVARCHAR(60),
@Description_7da1c4d9 NVARCHAR(MAX)
SET
  @ID_7da1c4d9 = '97A307B6-E7D6-5D7F-BF48-C3FCF0336517'
SET
  @ScoreModelID_7da1c4d9 = '05C13018-27B8-53DE-9D1D-129E6E15DF1C'
SET
  @RelatedEntityID_7da1c4d9 = '1928BDF7-D4EE-4C1B-B36D-CC3B9A4782AC'
SET
  @Alias_7da1c4d9 = N'competitions'
SET
  @RelationshipPath_7da1c4d9 = N'[]'
SET
  @JoinType_7da1c4d9 = N'Left' EXEC [__mj_BizAppsSonar].spCreateModelRelatedEntity @ID = @ID_7da1c4d9,
  @ScoreModelID = @ScoreModelID_7da1c4d9,
  @RelatedEntityID = @RelatedEntityID_7da1c4d9,
  @Alias = @Alias_7da1c4d9,
  @RelationshipPath = @RelationshipPath_7da1c4d9,
  @JoinType = @JoinType_7da1c4d9,
  @SourceSystemTag = @SourceSystemTag_7da1c4d9,
  @SourceSystemTag_Clear = 1,
  @Description = @Description_7da1c4d9,
  @Description_Clear = 1;

GO

-- Save MJ_BizApps_Sonar: Model Related Entities (core SP call only)
DECLARE @ID_b80ce2a6 UNIQUEIDENTIFIER,
@ScoreModelID_b80ce2a6 UNIQUEIDENTIFIER,
@RelatedEntityID_b80ce2a6 UNIQUEIDENTIFIER,
@Alias_b80ce2a6 NVARCHAR(100),
@RelationshipPath_b80ce2a6 NVARCHAR(MAX),
@JoinType_b80ce2a6 NVARCHAR(10),
@SourceSystemTag_b80ce2a6 NVARCHAR(60),
@Description_b80ce2a6 NVARCHAR(MAX)
SET
  @ID_b80ce2a6 = '543604CB-5EB4-5276-AD81-4F27D56B0023'
SET
  @ScoreModelID_b80ce2a6 = '05C13018-27B8-53DE-9D1D-129E6E15DF1C'
SET
  @RelatedEntityID_b80ce2a6 = '37C1AADD-E111-4604-AD2C-264775B1A076'
SET
  @Alias_b80ce2a6 = N'recentEvents'
SET
  @RelationshipPath_b80ce2a6 = N'[]'
SET
  @JoinType_b80ce2a6 = N'Left' EXEC [__mj_BizAppsSonar].spCreateModelRelatedEntity @ID = @ID_b80ce2a6,
  @ScoreModelID = @ScoreModelID_b80ce2a6,
  @RelatedEntityID = @RelatedEntityID_b80ce2a6,
  @Alias = @Alias_b80ce2a6,
  @RelationshipPath = @RelationshipPath_b80ce2a6,
  @JoinType = @JoinType_b80ce2a6,
  @SourceSystemTag = @SourceSystemTag_b80ce2a6,
  @SourceSystemTag_Clear = 1,
  @Description = @Description_b80ce2a6,
  @Description_Clear = 1;

GO

-- Save MJ_BizApps_Sonar: Model Related Entities (core SP call only)
DECLARE @ID_2bbdcb7c UNIQUEIDENTIFIER,
@ScoreModelID_2bbdcb7c UNIQUEIDENTIFIER,
@RelatedEntityID_2bbdcb7c UNIQUEIDENTIFIER,
@Alias_2bbdcb7c NVARCHAR(100),
@RelationshipPath_2bbdcb7c NVARCHAR(MAX),
@JoinType_2bbdcb7c NVARCHAR(10),
@SourceSystemTag_2bbdcb7c NVARCHAR(60),
@Description_2bbdcb7c NVARCHAR(MAX)
SET
  @ID_2bbdcb7c = '73A51ECF-B377-53F4-BFCF-04A2F9C85C1A'
SET
  @ScoreModelID_2bbdcb7c = '05C13018-27B8-53DE-9D1D-129E6E15DF1C'
SET
  @RelatedEntityID_2bbdcb7c = '63600739-7165-4BDC-B7D7-19A1B1951DFA'
SET
  @Alias_2bbdcb7c = N'surveyResponses'
SET
  @RelationshipPath_2bbdcb7c = N'[]'
SET
  @JoinType_2bbdcb7c = N'Left' EXEC [__mj_BizAppsSonar].spCreateModelRelatedEntity @ID = @ID_2bbdcb7c,
  @ScoreModelID = @ScoreModelID_2bbdcb7c,
  @RelatedEntityID = @RelatedEntityID_2bbdcb7c,
  @Alias = @Alias_2bbdcb7c,
  @RelationshipPath = @RelationshipPath_2bbdcb7c,
  @JoinType = @JoinType_2bbdcb7c,
  @SourceSystemTag = @SourceSystemTag_2bbdcb7c,
  @SourceSystemTag_Clear = 1,
  @Description = @Description_2bbdcb7c,
  @Description_Clear = 1;

GO

-- Save MJ_BizApps_Sonar: Factors (core SP call only)
DECLARE @ID_41820396 UNIQUEIDENTIFIER,
@Name_41820396 NVARCHAR(200),
@Slug_41820396 NVARCHAR(100),
@Description_41820396 NVARCHAR(MAX),
@ScoreModelID_41820396 UNIQUEIDENTIFIER,
@AnchorEntityID_41820396 UNIQUEIDENTIFIER,
@FactorType_41820396 NVARCHAR(20),
@SourceRelatedEntityID_41820396 UNIQUEIDENTIFIER,
@SourceEntityID_41820396 UNIQUEIDENTIFIER,
@FilterExpression_41820396 NVARCHAR(MAX),
@Aggregation_41820396 NVARCHAR(20),
@AggregateFieldName_41820396 NVARCHAR(200),
@TimeWindowID_41820396 UNIQUEIDENTIFIER,
@RecencyDecayHalfLifeDays_41820396 INT,
@ActionID_41820396 UNIQUEIDENTIFIER,
@ActionParamsJSON_41820396 NVARCHAR(MAX),
@ExecutionMode_41820396 NVARCHAR(12),
@IsExpensive_41820396 BIT,
@MaxConcurrency_41820396 INT,
@RateLimitPerMinute_41820396 INT,
@CacheTTLSeconds_41820396 INT,
@SourceScoreModelID_41820396 UNIQUEIDENTIFIER,
@RawDataType_41820396 NVARCHAR(12),
@NormalizationMethod_41820396 NVARCHAR(20),
@NormalizationParamsJSON_41820396 NVARCHAR(MAX),
@OutputMin_41820396 DECIMAL(9, 4),
@OutputMax_41820396 DECIMAL(9, 4),
@HigherIsBetter_41820396 BIT,
@PromotionState_41820396 NVARCHAR(20),
@LastValidatedAt_41820396 DATETIME2,
@CreatedByAgent_41820396 NVARCHAR(60),
@DateField_41820396 NVARCHAR(200)
SET
  @ID_41820396 = '83F3C3B5-D8DE-54DA-8969-BAA1D947D77B'
SET
  @Name_41820396 = N'Event Participation'
SET
  @Slug_41820396 = N'morecheese-event-participation'
SET
  @Description_41820396 = N'Events the member registered for in the last 12 months.'
SET
  @ScoreModelID_41820396 = '05C13018-27B8-53DE-9D1D-129E6E15DF1C'
SET
  @AnchorEntityID_41820396 = '7A94ADA9-7880-4FAE-97D8-DB0E934C3F5F'
SET
  @FactorType_41820396 = N'Declarative'
SET
  @SourceRelatedEntityID_41820396 = 'F0E5F480-36AB-5E85-B8B8-7C7255837A32'
SET
  @SourceEntityID_41820396 = '37C1AADD-E111-4604-AD2C-264775B1A076'
SET
  @Aggregation_41820396 = N'Count'
SET
  @TimeWindowID_41820396 = 'CF6F428F-7016-5898-BF94-22795E3B3F91'
SET
  @IsExpensive_41820396 = 0
SET
  @NormalizationMethod_41820396 = N'Percentile'
SET
  @HigherIsBetter_41820396 = 1
SET
  @PromotionState_41820396 = N'Approved'
SET
  @DateField_41820396 = N'RegisteredOn' EXEC [__mj_BizAppsSonar].spCreateFactor @ID = @ID_41820396,
  @Name = @Name_41820396,
  @Slug = @Slug_41820396,
  @Description = @Description_41820396,
  @ScoreModelID = @ScoreModelID_41820396,
  @AnchorEntityID = @AnchorEntityID_41820396,
  @FactorType = @FactorType_41820396,
  @SourceRelatedEntityID = @SourceRelatedEntityID_41820396,
  @SourceEntityID = @SourceEntityID_41820396,
  @FilterExpression = @FilterExpression_41820396,
  @FilterExpression_Clear = 1,
  @Aggregation = @Aggregation_41820396,
  @AggregateFieldName = @AggregateFieldName_41820396,
  @AggregateFieldName_Clear = 1,
  @TimeWindowID = @TimeWindowID_41820396,
  @RecencyDecayHalfLifeDays = @RecencyDecayHalfLifeDays_41820396,
  @RecencyDecayHalfLifeDays_Clear = 1,
  @ActionID = @ActionID_41820396,
  @ActionID_Clear = 1,
  @ActionParamsJSON = @ActionParamsJSON_41820396,
  @ActionParamsJSON_Clear = 1,
  @ExecutionMode = @ExecutionMode_41820396,
  @ExecutionMode_Clear = 1,
  @IsExpensive = @IsExpensive_41820396,
  @MaxConcurrency = @MaxConcurrency_41820396,
  @MaxConcurrency_Clear = 1,
  @RateLimitPerMinute = @RateLimitPerMinute_41820396,
  @RateLimitPerMinute_Clear = 1,
  @CacheTTLSeconds = @CacheTTLSeconds_41820396,
  @CacheTTLSeconds_Clear = 1,
  @SourceScoreModelID = @SourceScoreModelID_41820396,
  @SourceScoreModelID_Clear = 1,
  @RawDataType = @RawDataType_41820396,
  @RawDataType_Clear = 1,
  @NormalizationMethod = @NormalizationMethod_41820396,
  @NormalizationParamsJSON = @NormalizationParamsJSON_41820396,
  @NormalizationParamsJSON_Clear = 1,
  @OutputMin = @OutputMin_41820396,
  @OutputMin_Clear = 1,
  @OutputMax = @OutputMax_41820396,
  @OutputMax_Clear = 1,
  @HigherIsBetter = @HigherIsBetter_41820396,
  @PromotionState = @PromotionState_41820396,
  @LastValidatedAt = @LastValidatedAt_41820396,
  @LastValidatedAt_Clear = 1,
  @CreatedByAgent = @CreatedByAgent_41820396,
  @CreatedByAgent_Clear = 1,
  @DateField = @DateField_41820396;

GO

-- Save MJ_BizApps_Sonar: Factors (core SP call only)
DECLARE @ID_7075ec1c UNIQUEIDENTIFIER,
@Name_7075ec1c NVARCHAR(200),
@Slug_7075ec1c NVARCHAR(100),
@Description_7075ec1c NVARCHAR(MAX),
@ScoreModelID_7075ec1c UNIQUEIDENTIFIER,
@AnchorEntityID_7075ec1c UNIQUEIDENTIFIER,
@FactorType_7075ec1c NVARCHAR(20),
@SourceRelatedEntityID_7075ec1c UNIQUEIDENTIFIER,
@SourceEntityID_7075ec1c UNIQUEIDENTIFIER,
@FilterExpression_7075ec1c NVARCHAR(MAX),
@Aggregation_7075ec1c NVARCHAR(20),
@AggregateFieldName_7075ec1c NVARCHAR(200),
@TimeWindowID_7075ec1c UNIQUEIDENTIFIER,
@RecencyDecayHalfLifeDays_7075ec1c INT,
@ActionID_7075ec1c UNIQUEIDENTIFIER,
@ActionParamsJSON_7075ec1c NVARCHAR(MAX),
@ExecutionMode_7075ec1c NVARCHAR(12),
@IsExpensive_7075ec1c BIT,
@MaxConcurrency_7075ec1c INT,
@RateLimitPerMinute_7075ec1c INT,
@CacheTTLSeconds_7075ec1c INT,
@SourceScoreModelID_7075ec1c UNIQUEIDENTIFIER,
@RawDataType_7075ec1c NVARCHAR(12),
@NormalizationMethod_7075ec1c NVARCHAR(20),
@NormalizationParamsJSON_7075ec1c NVARCHAR(MAX),
@OutputMin_7075ec1c DECIMAL(9, 4),
@OutputMax_7075ec1c DECIMAL(9, 4),
@HigherIsBetter_7075ec1c BIT,
@PromotionState_7075ec1c NVARCHAR(20),
@LastValidatedAt_7075ec1c DATETIME2,
@CreatedByAgent_7075ec1c NVARCHAR(60),
@DateField_7075ec1c NVARCHAR(200)
SET
  @ID_7075ec1c = '570029BF-9C80-5C72-9914-E99D12C338B1'
SET
  @Name_7075ec1c = N'Committee Service'
SET
  @Slug_7075ec1c = N'morecheese-committee-service'
SET
  @Description_7075ec1c = N'Committee memberships the member holds.'
SET
  @ScoreModelID_7075ec1c = '05C13018-27B8-53DE-9D1D-129E6E15DF1C'
SET
  @AnchorEntityID_7075ec1c = '7A94ADA9-7880-4FAE-97D8-DB0E934C3F5F'
SET
  @FactorType_7075ec1c = N'Declarative'
SET
  @SourceRelatedEntityID_7075ec1c = '1513A3B7-DC66-57D2-9FC5-F364F3147205'
SET
  @SourceEntityID_7075ec1c = 'F8FADBBE-A323-48FB-8395-3B543729F6E6'
SET
  @Aggregation_7075ec1c = N'Count'
SET
  @IsExpensive_7075ec1c = 0
SET
  @NormalizationMethod_7075ec1c = N'Percentile'
SET
  @HigherIsBetter_7075ec1c = 1
SET
  @PromotionState_7075ec1c = N'Approved' EXEC [__mj_BizAppsSonar].spCreateFactor @ID = @ID_7075ec1c,
  @Name = @Name_7075ec1c,
  @Slug = @Slug_7075ec1c,
  @Description = @Description_7075ec1c,
  @ScoreModelID = @ScoreModelID_7075ec1c,
  @AnchorEntityID = @AnchorEntityID_7075ec1c,
  @FactorType = @FactorType_7075ec1c,
  @SourceRelatedEntityID = @SourceRelatedEntityID_7075ec1c,
  @SourceEntityID = @SourceEntityID_7075ec1c,
  @FilterExpression = @FilterExpression_7075ec1c,
  @FilterExpression_Clear = 1,
  @Aggregation = @Aggregation_7075ec1c,
  @AggregateFieldName = @AggregateFieldName_7075ec1c,
  @AggregateFieldName_Clear = 1,
  @TimeWindowID = @TimeWindowID_7075ec1c,
  @TimeWindowID_Clear = 1,
  @RecencyDecayHalfLifeDays = @RecencyDecayHalfLifeDays_7075ec1c,
  @RecencyDecayHalfLifeDays_Clear = 1,
  @ActionID = @ActionID_7075ec1c,
  @ActionID_Clear = 1,
  @ActionParamsJSON = @ActionParamsJSON_7075ec1c,
  @ActionParamsJSON_Clear = 1,
  @ExecutionMode = @ExecutionMode_7075ec1c,
  @ExecutionMode_Clear = 1,
  @IsExpensive = @IsExpensive_7075ec1c,
  @MaxConcurrency = @MaxConcurrency_7075ec1c,
  @MaxConcurrency_Clear = 1,
  @RateLimitPerMinute = @RateLimitPerMinute_7075ec1c,
  @RateLimitPerMinute_Clear = 1,
  @CacheTTLSeconds = @CacheTTLSeconds_7075ec1c,
  @CacheTTLSeconds_Clear = 1,
  @SourceScoreModelID = @SourceScoreModelID_7075ec1c,
  @SourceScoreModelID_Clear = 1,
  @RawDataType = @RawDataType_7075ec1c,
  @RawDataType_Clear = 1,
  @NormalizationMethod = @NormalizationMethod_7075ec1c,
  @NormalizationParamsJSON = @NormalizationParamsJSON_7075ec1c,
  @NormalizationParamsJSON_Clear = 1,
  @OutputMin = @OutputMin_7075ec1c,
  @OutputMin_Clear = 1,
  @OutputMax = @OutputMax_7075ec1c,
  @OutputMax_Clear = 1,
  @HigherIsBetter = @HigherIsBetter_7075ec1c,
  @PromotionState = @PromotionState_7075ec1c,
  @LastValidatedAt = @LastValidatedAt_7075ec1c,
  @LastValidatedAt_Clear = 1,
  @CreatedByAgent = @CreatedByAgent_7075ec1c,
  @CreatedByAgent_Clear = 1,
  @DateField = @DateField_7075ec1c,
  @DateField_Clear = 1;

GO

-- Save MJ_BizApps_Sonar: Factors (core SP call only)
DECLARE @ID_991f43d2 UNIQUEIDENTIFIER,
@Name_991f43d2 NVARCHAR(200),
@Slug_991f43d2 NVARCHAR(100),
@Description_991f43d2 NVARCHAR(MAX),
@ScoreModelID_991f43d2 UNIQUEIDENTIFIER,
@AnchorEntityID_991f43d2 UNIQUEIDENTIFIER,
@FactorType_991f43d2 NVARCHAR(20),
@SourceRelatedEntityID_991f43d2 UNIQUEIDENTIFIER,
@SourceEntityID_991f43d2 UNIQUEIDENTIFIER,
@FilterExpression_991f43d2 NVARCHAR(MAX),
@Aggregation_991f43d2 NVARCHAR(20),
@AggregateFieldName_991f43d2 NVARCHAR(200),
@TimeWindowID_991f43d2 UNIQUEIDENTIFIER,
@RecencyDecayHalfLifeDays_991f43d2 INT,
@ActionID_991f43d2 UNIQUEIDENTIFIER,
@ActionParamsJSON_991f43d2 NVARCHAR(MAX),
@ExecutionMode_991f43d2 NVARCHAR(12),
@IsExpensive_991f43d2 BIT,
@MaxConcurrency_991f43d2 INT,
@RateLimitPerMinute_991f43d2 INT,
@CacheTTLSeconds_991f43d2 INT,
@SourceScoreModelID_991f43d2 UNIQUEIDENTIFIER,
@RawDataType_991f43d2 NVARCHAR(12),
@NormalizationMethod_991f43d2 NVARCHAR(20),
@NormalizationParamsJSON_991f43d2 NVARCHAR(MAX),
@OutputMin_991f43d2 DECIMAL(9, 4),
@OutputMax_991f43d2 DECIMAL(9, 4),
@HigherIsBetter_991f43d2 BIT,
@PromotionState_991f43d2 NVARCHAR(20),
@LastValidatedAt_991f43d2 DATETIME2,
@CreatedByAgent_991f43d2 NVARCHAR(60),
@DateField_991f43d2 NVARCHAR(200)
SET
  @ID_991f43d2 = '7A2C147C-A4DB-5DAD-AB01-A99344A4AA82'
SET
  @Name_991f43d2 = N'Certifications'
SET
  @Slug_991f43d2 = N'morecheese-certifications'
SET
  @Description_991f43d2 = N'Certifications the member has pursued or earned.'
SET
  @ScoreModelID_991f43d2 = '05C13018-27B8-53DE-9D1D-129E6E15DF1C'
SET
  @AnchorEntityID_991f43d2 = '7A94ADA9-7880-4FAE-97D8-DB0E934C3F5F'
SET
  @FactorType_991f43d2 = N'Declarative'
SET
  @SourceRelatedEntityID_991f43d2 = 'E5508983-6C7F-5379-8537-FB54E23630FE'
SET
  @SourceEntityID_991f43d2 = 'F4D4BA79-C264-45C6-9A51-A00571ABCD6B'
SET
  @Aggregation_991f43d2 = N'Count'
SET
  @IsExpensive_991f43d2 = 0
SET
  @NormalizationMethod_991f43d2 = N'Percentile'
SET
  @HigherIsBetter_991f43d2 = 1
SET
  @PromotionState_991f43d2 = N'Approved' EXEC [__mj_BizAppsSonar].spCreateFactor @ID = @ID_991f43d2,
  @Name = @Name_991f43d2,
  @Slug = @Slug_991f43d2,
  @Description = @Description_991f43d2,
  @ScoreModelID = @ScoreModelID_991f43d2,
  @AnchorEntityID = @AnchorEntityID_991f43d2,
  @FactorType = @FactorType_991f43d2,
  @SourceRelatedEntityID = @SourceRelatedEntityID_991f43d2,
  @SourceEntityID = @SourceEntityID_991f43d2,
  @FilterExpression = @FilterExpression_991f43d2,
  @FilterExpression_Clear = 1,
  @Aggregation = @Aggregation_991f43d2,
  @AggregateFieldName = @AggregateFieldName_991f43d2,
  @AggregateFieldName_Clear = 1,
  @TimeWindowID = @TimeWindowID_991f43d2,
  @TimeWindowID_Clear = 1,
  @RecencyDecayHalfLifeDays = @RecencyDecayHalfLifeDays_991f43d2,
  @RecencyDecayHalfLifeDays_Clear = 1,
  @ActionID = @ActionID_991f43d2,
  @ActionID_Clear = 1,
  @ActionParamsJSON = @ActionParamsJSON_991f43d2,
  @ActionParamsJSON_Clear = 1,
  @ExecutionMode = @ExecutionMode_991f43d2,
  @ExecutionMode_Clear = 1,
  @IsExpensive = @IsExpensive_991f43d2,
  @MaxConcurrency = @MaxConcurrency_991f43d2,
  @MaxConcurrency_Clear = 1,
  @RateLimitPerMinute = @RateLimitPerMinute_991f43d2,
  @RateLimitPerMinute_Clear = 1,
  @CacheTTLSeconds = @CacheTTLSeconds_991f43d2,
  @CacheTTLSeconds_Clear = 1,
  @SourceScoreModelID = @SourceScoreModelID_991f43d2,
  @SourceScoreModelID_Clear = 1,
  @RawDataType = @RawDataType_991f43d2,
  @RawDataType_Clear = 1,
  @NormalizationMethod = @NormalizationMethod_991f43d2,
  @NormalizationParamsJSON = @NormalizationParamsJSON_991f43d2,
  @NormalizationParamsJSON_Clear = 1,
  @OutputMin = @OutputMin_991f43d2,
  @OutputMin_Clear = 1,
  @OutputMax = @OutputMax_991f43d2,
  @OutputMax_Clear = 1,
  @HigherIsBetter = @HigherIsBetter_991f43d2,
  @PromotionState = @PromotionState_991f43d2,
  @LastValidatedAt = @LastValidatedAt_991f43d2,
  @LastValidatedAt_Clear = 1,
  @CreatedByAgent = @CreatedByAgent_991f43d2,
  @CreatedByAgent_Clear = 1,
  @DateField = @DateField_991f43d2,
  @DateField_Clear = 1;

GO

-- Save MJ_BizApps_Sonar: Factors (core SP call only)
DECLARE @ID_c30b8223 UNIQUEIDENTIFIER,
@Name_c30b8223 NVARCHAR(200),
@Slug_c30b8223 NVARCHAR(100),
@Description_c30b8223 NVARCHAR(MAX),
@ScoreModelID_c30b8223 UNIQUEIDENTIFIER,
@AnchorEntityID_c30b8223 UNIQUEIDENTIFIER,
@FactorType_c30b8223 NVARCHAR(20),
@SourceRelatedEntityID_c30b8223 UNIQUEIDENTIFIER,
@SourceEntityID_c30b8223 UNIQUEIDENTIFIER,
@FilterExpression_c30b8223 NVARCHAR(MAX),
@Aggregation_c30b8223 NVARCHAR(20),
@AggregateFieldName_c30b8223 NVARCHAR(200),
@TimeWindowID_c30b8223 UNIQUEIDENTIFIER,
@RecencyDecayHalfLifeDays_c30b8223 INT,
@ActionID_c30b8223 UNIQUEIDENTIFIER,
@ActionParamsJSON_c30b8223 NVARCHAR(MAX),
@ExecutionMode_c30b8223 NVARCHAR(12),
@IsExpensive_c30b8223 BIT,
@MaxConcurrency_c30b8223 INT,
@RateLimitPerMinute_c30b8223 INT,
@CacheTTLSeconds_c30b8223 INT,
@SourceScoreModelID_c30b8223 UNIQUEIDENTIFIER,
@RawDataType_c30b8223 NVARCHAR(12),
@NormalizationMethod_c30b8223 NVARCHAR(20),
@NormalizationParamsJSON_c30b8223 NVARCHAR(MAX),
@OutputMin_c30b8223 DECIMAL(9, 4),
@OutputMax_c30b8223 DECIMAL(9, 4),
@HigherIsBetter_c30b8223 BIT,
@PromotionState_c30b8223 NVARCHAR(20),
@LastValidatedAt_c30b8223 DATETIME2,
@CreatedByAgent_c30b8223 NVARCHAR(60),
@DateField_c30b8223 NVARCHAR(200)
SET
  @ID_c30b8223 = '9DD8C3C8-7F39-5058-A8BA-D830EA41832D'
SET
  @Name_c30b8223 = N'Learning Activity'
SET
  @Slug_c30b8223 = N'morecheese-learning-activity'
SET
  @Description_c30b8223 = N'Courses the member enrolled in over the last 12 months.'
SET
  @ScoreModelID_c30b8223 = '05C13018-27B8-53DE-9D1D-129E6E15DF1C'
SET
  @AnchorEntityID_c30b8223 = '7A94ADA9-7880-4FAE-97D8-DB0E934C3F5F'
SET
  @FactorType_c30b8223 = N'Declarative'
SET
  @SourceRelatedEntityID_c30b8223 = '8032E327-83FA-5297-A791-EE91AD2CABC5'
SET
  @SourceEntityID_c30b8223 = 'FE8BF319-06BC-4E03-A22A-7864DB37579F'
SET
  @Aggregation_c30b8223 = N'Count'
SET
  @TimeWindowID_c30b8223 = 'CF6F428F-7016-5898-BF94-22795E3B3F91'
SET
  @IsExpensive_c30b8223 = 0
SET
  @NormalizationMethod_c30b8223 = N'Percentile'
SET
  @HigherIsBetter_c30b8223 = 1
SET
  @PromotionState_c30b8223 = N'Approved'
SET
  @DateField_c30b8223 = N'EnrolledOn' EXEC [__mj_BizAppsSonar].spCreateFactor @ID = @ID_c30b8223,
  @Name = @Name_c30b8223,
  @Slug = @Slug_c30b8223,
  @Description = @Description_c30b8223,
  @ScoreModelID = @ScoreModelID_c30b8223,
  @AnchorEntityID = @AnchorEntityID_c30b8223,
  @FactorType = @FactorType_c30b8223,
  @SourceRelatedEntityID = @SourceRelatedEntityID_c30b8223,
  @SourceEntityID = @SourceEntityID_c30b8223,
  @FilterExpression = @FilterExpression_c30b8223,
  @FilterExpression_Clear = 1,
  @Aggregation = @Aggregation_c30b8223,
  @AggregateFieldName = @AggregateFieldName_c30b8223,
  @AggregateFieldName_Clear = 1,
  @TimeWindowID = @TimeWindowID_c30b8223,
  @RecencyDecayHalfLifeDays = @RecencyDecayHalfLifeDays_c30b8223,
  @RecencyDecayHalfLifeDays_Clear = 1,
  @ActionID = @ActionID_c30b8223,
  @ActionID_Clear = 1,
  @ActionParamsJSON = @ActionParamsJSON_c30b8223,
  @ActionParamsJSON_Clear = 1,
  @ExecutionMode = @ExecutionMode_c30b8223,
  @ExecutionMode_Clear = 1,
  @IsExpensive = @IsExpensive_c30b8223,
  @MaxConcurrency = @MaxConcurrency_c30b8223,
  @MaxConcurrency_Clear = 1,
  @RateLimitPerMinute = @RateLimitPerMinute_c30b8223,
  @RateLimitPerMinute_Clear = 1,
  @CacheTTLSeconds = @CacheTTLSeconds_c30b8223,
  @CacheTTLSeconds_Clear = 1,
  @SourceScoreModelID = @SourceScoreModelID_c30b8223,
  @SourceScoreModelID_Clear = 1,
  @RawDataType = @RawDataType_c30b8223,
  @RawDataType_Clear = 1,
  @NormalizationMethod = @NormalizationMethod_c30b8223,
  @NormalizationParamsJSON = @NormalizationParamsJSON_c30b8223,
  @NormalizationParamsJSON_Clear = 1,
  @OutputMin = @OutputMin_c30b8223,
  @OutputMin_Clear = 1,
  @OutputMax = @OutputMax_c30b8223,
  @OutputMax_Clear = 1,
  @HigherIsBetter = @HigherIsBetter_c30b8223,
  @PromotionState = @PromotionState_c30b8223,
  @LastValidatedAt = @LastValidatedAt_c30b8223,
  @LastValidatedAt_Clear = 1,
  @CreatedByAgent = @CreatedByAgent_c30b8223,
  @CreatedByAgent_Clear = 1,
  @DateField = @DateField_c30b8223;

GO

-- Save MJ_BizApps_Sonar: Factors (core SP call only)
DECLARE @ID_2dc6ec6d UNIQUEIDENTIFIER,
@Name_2dc6ec6d NVARCHAR(200),
@Slug_2dc6ec6d NVARCHAR(100),
@Description_2dc6ec6d NVARCHAR(MAX),
@ScoreModelID_2dc6ec6d UNIQUEIDENTIFIER,
@AnchorEntityID_2dc6ec6d UNIQUEIDENTIFIER,
@FactorType_2dc6ec6d NVARCHAR(20),
@SourceRelatedEntityID_2dc6ec6d UNIQUEIDENTIFIER,
@SourceEntityID_2dc6ec6d UNIQUEIDENTIFIER,
@FilterExpression_2dc6ec6d NVARCHAR(MAX),
@Aggregation_2dc6ec6d NVARCHAR(20),
@AggregateFieldName_2dc6ec6d NVARCHAR(200),
@TimeWindowID_2dc6ec6d UNIQUEIDENTIFIER,
@RecencyDecayHalfLifeDays_2dc6ec6d INT,
@ActionID_2dc6ec6d UNIQUEIDENTIFIER,
@ActionParamsJSON_2dc6ec6d NVARCHAR(MAX),
@ExecutionMode_2dc6ec6d NVARCHAR(12),
@IsExpensive_2dc6ec6d BIT,
@MaxConcurrency_2dc6ec6d INT,
@RateLimitPerMinute_2dc6ec6d INT,
@CacheTTLSeconds_2dc6ec6d INT,
@SourceScoreModelID_2dc6ec6d UNIQUEIDENTIFIER,
@RawDataType_2dc6ec6d NVARCHAR(12),
@NormalizationMethod_2dc6ec6d NVARCHAR(20),
@NormalizationParamsJSON_2dc6ec6d NVARCHAR(MAX),
@OutputMin_2dc6ec6d DECIMAL(9, 4),
@OutputMax_2dc6ec6d DECIMAL(9, 4),
@HigherIsBetter_2dc6ec6d BIT,
@PromotionState_2dc6ec6d NVARCHAR(20),
@LastValidatedAt_2dc6ec6d DATETIME2,
@CreatedByAgent_2dc6ec6d NVARCHAR(60),
@DateField_2dc6ec6d NVARCHAR(200)
SET
  @ID_2dc6ec6d = '1A860AAD-8767-5E2A-9ECE-C359C3D4EC1F'
SET
  @Name_2dc6ec6d = N'Advocacy Participation'
SET
  @Slug_2dc6ec6d = N'morecheese-advocacy-participation'
SET
  @Description_2dc6ec6d = N'Advocacy actions the member took over the last 24 months.'
SET
  @ScoreModelID_2dc6ec6d = '05C13018-27B8-53DE-9D1D-129E6E15DF1C'
SET
  @AnchorEntityID_2dc6ec6d = '7A94ADA9-7880-4FAE-97D8-DB0E934C3F5F'
SET
  @FactorType_2dc6ec6d = N'Declarative'
SET
  @SourceRelatedEntityID_2dc6ec6d = '123C5F43-B18B-5C63-AF54-4D6E3015635F'
SET
  @SourceEntityID_2dc6ec6d = '318E1216-842B-4EF7-8AD5-FCC4FC83E16E'
SET
  @Aggregation_2dc6ec6d = N'Count'
SET
  @TimeWindowID_2dc6ec6d = '97DF3796-A479-558E-9927-755A48D0D061'
SET
  @IsExpensive_2dc6ec6d = 0
SET
  @NormalizationMethod_2dc6ec6d = N'Percentile'
SET
  @HigherIsBetter_2dc6ec6d = 1
SET
  @PromotionState_2dc6ec6d = N'Approved'
SET
  @DateField_2dc6ec6d = N'ActionDate' EXEC [__mj_BizAppsSonar].spCreateFactor @ID = @ID_2dc6ec6d,
  @Name = @Name_2dc6ec6d,
  @Slug = @Slug_2dc6ec6d,
  @Description = @Description_2dc6ec6d,
  @ScoreModelID = @ScoreModelID_2dc6ec6d,
  @AnchorEntityID = @AnchorEntityID_2dc6ec6d,
  @FactorType = @FactorType_2dc6ec6d,
  @SourceRelatedEntityID = @SourceRelatedEntityID_2dc6ec6d,
  @SourceEntityID = @SourceEntityID_2dc6ec6d,
  @FilterExpression = @FilterExpression_2dc6ec6d,
  @FilterExpression_Clear = 1,
  @Aggregation = @Aggregation_2dc6ec6d,
  @AggregateFieldName = @AggregateFieldName_2dc6ec6d,
  @AggregateFieldName_Clear = 1,
  @TimeWindowID = @TimeWindowID_2dc6ec6d,
  @RecencyDecayHalfLifeDays = @RecencyDecayHalfLifeDays_2dc6ec6d,
  @RecencyDecayHalfLifeDays_Clear = 1,
  @ActionID = @ActionID_2dc6ec6d,
  @ActionID_Clear = 1,
  @ActionParamsJSON = @ActionParamsJSON_2dc6ec6d,
  @ActionParamsJSON_Clear = 1,
  @ExecutionMode = @ExecutionMode_2dc6ec6d,
  @ExecutionMode_Clear = 1,
  @IsExpensive = @IsExpensive_2dc6ec6d,
  @MaxConcurrency = @MaxConcurrency_2dc6ec6d,
  @MaxConcurrency_Clear = 1,
  @RateLimitPerMinute = @RateLimitPerMinute_2dc6ec6d,
  @RateLimitPerMinute_Clear = 1,
  @CacheTTLSeconds = @CacheTTLSeconds_2dc6ec6d,
  @CacheTTLSeconds_Clear = 1,
  @SourceScoreModelID = @SourceScoreModelID_2dc6ec6d,
  @SourceScoreModelID_Clear = 1,
  @RawDataType = @RawDataType_2dc6ec6d,
  @RawDataType_Clear = 1,
  @NormalizationMethod = @NormalizationMethod_2dc6ec6d,
  @NormalizationParamsJSON = @NormalizationParamsJSON_2dc6ec6d,
  @NormalizationParamsJSON_Clear = 1,
  @OutputMin = @OutputMin_2dc6ec6d,
  @OutputMin_Clear = 1,
  @OutputMax = @OutputMax_2dc6ec6d,
  @OutputMax_Clear = 1,
  @HigherIsBetter = @HigherIsBetter_2dc6ec6d,
  @PromotionState = @PromotionState_2dc6ec6d,
  @LastValidatedAt = @LastValidatedAt_2dc6ec6d,
  @LastValidatedAt_Clear = 1,
  @CreatedByAgent = @CreatedByAgent_2dc6ec6d,
  @CreatedByAgent_Clear = 1,
  @DateField = @DateField_2dc6ec6d;

GO

-- Save MJ_BizApps_Sonar: Factors (core SP call only)
DECLARE @ID_e1139dd0 UNIQUEIDENTIFIER,
@Name_e1139dd0 NVARCHAR(200),
@Slug_e1139dd0 NVARCHAR(100),
@Description_e1139dd0 NVARCHAR(MAX),
@ScoreModelID_e1139dd0 UNIQUEIDENTIFIER,
@AnchorEntityID_e1139dd0 UNIQUEIDENTIFIER,
@FactorType_e1139dd0 NVARCHAR(20),
@SourceRelatedEntityID_e1139dd0 UNIQUEIDENTIFIER,
@SourceEntityID_e1139dd0 UNIQUEIDENTIFIER,
@FilterExpression_e1139dd0 NVARCHAR(MAX),
@Aggregation_e1139dd0 NVARCHAR(20),
@AggregateFieldName_e1139dd0 NVARCHAR(200),
@TimeWindowID_e1139dd0 UNIQUEIDENTIFIER,
@RecencyDecayHalfLifeDays_e1139dd0 INT,
@ActionID_e1139dd0 UNIQUEIDENTIFIER,
@ActionParamsJSON_e1139dd0 NVARCHAR(MAX),
@ExecutionMode_e1139dd0 NVARCHAR(12),
@IsExpensive_e1139dd0 BIT,
@MaxConcurrency_e1139dd0 INT,
@RateLimitPerMinute_e1139dd0 INT,
@CacheTTLSeconds_e1139dd0 INT,
@SourceScoreModelID_e1139dd0 UNIQUEIDENTIFIER,
@RawDataType_e1139dd0 NVARCHAR(12),
@NormalizationMethod_e1139dd0 NVARCHAR(20),
@NormalizationParamsJSON_e1139dd0 NVARCHAR(MAX),
@OutputMin_e1139dd0 DECIMAL(9, 4),
@OutputMax_e1139dd0 DECIMAL(9, 4),
@HigherIsBetter_e1139dd0 BIT,
@PromotionState_e1139dd0 NVARCHAR(20),
@LastValidatedAt_e1139dd0 DATETIME2,
@CreatedByAgent_e1139dd0 NVARCHAR(60),
@DateField_e1139dd0 NVARCHAR(200)
SET
  @ID_e1139dd0 = 'EC18FBE8-6AA4-5FF4-BAE7-7B2AD248EA49'
SET
  @Name_e1139dd0 = N'Competition Entries'
SET
  @Slug_e1139dd0 = N'morecheese-competition-entries'
SET
  @Description_e1139dd0 = N'Cheese competition entries the member has submitted.'
SET
  @ScoreModelID_e1139dd0 = '05C13018-27B8-53DE-9D1D-129E6E15DF1C'
SET
  @AnchorEntityID_e1139dd0 = '7A94ADA9-7880-4FAE-97D8-DB0E934C3F5F'
SET
  @FactorType_e1139dd0 = N'Declarative'
SET
  @SourceRelatedEntityID_e1139dd0 = '97A307B6-E7D6-5D7F-BF48-C3FCF0336517'
SET
  @SourceEntityID_e1139dd0 = '1928BDF7-D4EE-4C1B-B36D-CC3B9A4782AC'
SET
  @Aggregation_e1139dd0 = N'Count'
SET
  @IsExpensive_e1139dd0 = 0
SET
  @NormalizationMethod_e1139dd0 = N'Percentile'
SET
  @HigherIsBetter_e1139dd0 = 1
SET
  @PromotionState_e1139dd0 = N'Approved' EXEC [__mj_BizAppsSonar].spCreateFactor @ID = @ID_e1139dd0,
  @Name = @Name_e1139dd0,
  @Slug = @Slug_e1139dd0,
  @Description = @Description_e1139dd0,
  @ScoreModelID = @ScoreModelID_e1139dd0,
  @AnchorEntityID = @AnchorEntityID_e1139dd0,
  @FactorType = @FactorType_e1139dd0,
  @SourceRelatedEntityID = @SourceRelatedEntityID_e1139dd0,
  @SourceEntityID = @SourceEntityID_e1139dd0,
  @FilterExpression = @FilterExpression_e1139dd0,
  @FilterExpression_Clear = 1,
  @Aggregation = @Aggregation_e1139dd0,
  @AggregateFieldName = @AggregateFieldName_e1139dd0,
  @AggregateFieldName_Clear = 1,
  @TimeWindowID = @TimeWindowID_e1139dd0,
  @TimeWindowID_Clear = 1,
  @RecencyDecayHalfLifeDays = @RecencyDecayHalfLifeDays_e1139dd0,
  @RecencyDecayHalfLifeDays_Clear = 1,
  @ActionID = @ActionID_e1139dd0,
  @ActionID_Clear = 1,
  @ActionParamsJSON = @ActionParamsJSON_e1139dd0,
  @ActionParamsJSON_Clear = 1,
  @ExecutionMode = @ExecutionMode_e1139dd0,
  @ExecutionMode_Clear = 1,
  @IsExpensive = @IsExpensive_e1139dd0,
  @MaxConcurrency = @MaxConcurrency_e1139dd0,
  @MaxConcurrency_Clear = 1,
  @RateLimitPerMinute = @RateLimitPerMinute_e1139dd0,
  @RateLimitPerMinute_Clear = 1,
  @CacheTTLSeconds = @CacheTTLSeconds_e1139dd0,
  @CacheTTLSeconds_Clear = 1,
  @SourceScoreModelID = @SourceScoreModelID_e1139dd0,
  @SourceScoreModelID_Clear = 1,
  @RawDataType = @RawDataType_e1139dd0,
  @RawDataType_Clear = 1,
  @NormalizationMethod = @NormalizationMethod_e1139dd0,
  @NormalizationParamsJSON = @NormalizationParamsJSON_e1139dd0,
  @NormalizationParamsJSON_Clear = 1,
  @OutputMin = @OutputMin_e1139dd0,
  @OutputMin_Clear = 1,
  @OutputMax = @OutputMax_e1139dd0,
  @OutputMax_Clear = 1,
  @HigherIsBetter = @HigherIsBetter_e1139dd0,
  @PromotionState = @PromotionState_e1139dd0,
  @LastValidatedAt = @LastValidatedAt_e1139dd0,
  @LastValidatedAt_Clear = 1,
  @CreatedByAgent = @CreatedByAgent_e1139dd0,
  @CreatedByAgent_Clear = 1,
  @DateField = @DateField_e1139dd0,
  @DateField_Clear = 1;

GO

-- Save MJ_BizApps_Sonar: Factors (core SP call only)
DECLARE @ID_eaa2edb4 UNIQUEIDENTIFIER,
@Name_eaa2edb4 NVARCHAR(200),
@Slug_eaa2edb4 NVARCHAR(100),
@Description_eaa2edb4 NVARCHAR(MAX),
@ScoreModelID_eaa2edb4 UNIQUEIDENTIFIER,
@AnchorEntityID_eaa2edb4 UNIQUEIDENTIFIER,
@FactorType_eaa2edb4 NVARCHAR(20),
@SourceRelatedEntityID_eaa2edb4 UNIQUEIDENTIFIER,
@SourceEntityID_eaa2edb4 UNIQUEIDENTIFIER,
@FilterExpression_eaa2edb4 NVARCHAR(MAX),
@Aggregation_eaa2edb4 NVARCHAR(20),
@AggregateFieldName_eaa2edb4 NVARCHAR(200),
@TimeWindowID_eaa2edb4 UNIQUEIDENTIFIER,
@RecencyDecayHalfLifeDays_eaa2edb4 INT,
@ActionID_eaa2edb4 UNIQUEIDENTIFIER,
@ActionParamsJSON_eaa2edb4 NVARCHAR(MAX),
@ExecutionMode_eaa2edb4 NVARCHAR(12),
@IsExpensive_eaa2edb4 BIT,
@MaxConcurrency_eaa2edb4 INT,
@RateLimitPerMinute_eaa2edb4 INT,
@CacheTTLSeconds_eaa2edb4 INT,
@SourceScoreModelID_eaa2edb4 UNIQUEIDENTIFIER,
@RawDataType_eaa2edb4 NVARCHAR(12),
@NormalizationMethod_eaa2edb4 NVARCHAR(20),
@NormalizationParamsJSON_eaa2edb4 NVARCHAR(MAX),
@OutputMin_eaa2edb4 DECIMAL(9, 4),
@OutputMax_eaa2edb4 DECIMAL(9, 4),
@HigherIsBetter_eaa2edb4 BIT,
@PromotionState_eaa2edb4 NVARCHAR(20),
@LastValidatedAt_eaa2edb4 DATETIME2,
@CreatedByAgent_eaa2edb4 NVARCHAR(60),
@DateField_eaa2edb4 NVARCHAR(200)
SET
  @ID_eaa2edb4 = '2C7B495A-61FE-553A-B219-B5F576E23278'
SET
  @Name_eaa2edb4 = N'Event Recency'
SET
  @Slug_eaa2edb4 = N'morecheese-event-recency'
SET
  @Description_eaa2edb4 = N'How recently the member last attended an event (sooner is better).'
SET
  @ScoreModelID_eaa2edb4 = '05C13018-27B8-53DE-9D1D-129E6E15DF1C'
SET
  @AnchorEntityID_eaa2edb4 = '7A94ADA9-7880-4FAE-97D8-DB0E934C3F5F'
SET
  @FactorType_eaa2edb4 = N'Declarative'
SET
  @SourceRelatedEntityID_eaa2edb4 = '543604CB-5EB4-5276-AD81-4F27D56B0023'
SET
  @SourceEntityID_eaa2edb4 = '37C1AADD-E111-4604-AD2C-264775B1A076'
SET
  @Aggregation_eaa2edb4 = N'Recency'
SET
  @AggregateFieldName_eaa2edb4 = N'RegisteredOn'
SET
  @IsExpensive_eaa2edb4 = 0
SET
  @NormalizationMethod_eaa2edb4 = N'Percentile'
SET
  @HigherIsBetter_eaa2edb4 = 0
SET
  @PromotionState_eaa2edb4 = N'Approved' EXEC [__mj_BizAppsSonar].spCreateFactor @ID = @ID_eaa2edb4,
  @Name = @Name_eaa2edb4,
  @Slug = @Slug_eaa2edb4,
  @Description = @Description_eaa2edb4,
  @ScoreModelID = @ScoreModelID_eaa2edb4,
  @AnchorEntityID = @AnchorEntityID_eaa2edb4,
  @FactorType = @FactorType_eaa2edb4,
  @SourceRelatedEntityID = @SourceRelatedEntityID_eaa2edb4,
  @SourceEntityID = @SourceEntityID_eaa2edb4,
  @FilterExpression = @FilterExpression_eaa2edb4,
  @FilterExpression_Clear = 1,
  @Aggregation = @Aggregation_eaa2edb4,
  @AggregateFieldName = @AggregateFieldName_eaa2edb4,
  @TimeWindowID = @TimeWindowID_eaa2edb4,
  @TimeWindowID_Clear = 1,
  @RecencyDecayHalfLifeDays = @RecencyDecayHalfLifeDays_eaa2edb4,
  @RecencyDecayHalfLifeDays_Clear = 1,
  @ActionID = @ActionID_eaa2edb4,
  @ActionID_Clear = 1,
  @ActionParamsJSON = @ActionParamsJSON_eaa2edb4,
  @ActionParamsJSON_Clear = 1,
  @ExecutionMode = @ExecutionMode_eaa2edb4,
  @ExecutionMode_Clear = 1,
  @IsExpensive = @IsExpensive_eaa2edb4,
  @MaxConcurrency = @MaxConcurrency_eaa2edb4,
  @MaxConcurrency_Clear = 1,
  @RateLimitPerMinute = @RateLimitPerMinute_eaa2edb4,
  @RateLimitPerMinute_Clear = 1,
  @CacheTTLSeconds = @CacheTTLSeconds_eaa2edb4,
  @CacheTTLSeconds_Clear = 1,
  @SourceScoreModelID = @SourceScoreModelID_eaa2edb4,
  @SourceScoreModelID_Clear = 1,
  @RawDataType = @RawDataType_eaa2edb4,
  @RawDataType_Clear = 1,
  @NormalizationMethod = @NormalizationMethod_eaa2edb4,
  @NormalizationParamsJSON = @NormalizationParamsJSON_eaa2edb4,
  @NormalizationParamsJSON_Clear = 1,
  @OutputMin = @OutputMin_eaa2edb4,
  @OutputMin_Clear = 1,
  @OutputMax = @OutputMax_eaa2edb4,
  @OutputMax_Clear = 1,
  @HigherIsBetter = @HigherIsBetter_eaa2edb4,
  @PromotionState = @PromotionState_eaa2edb4,
  @LastValidatedAt = @LastValidatedAt_eaa2edb4,
  @LastValidatedAt_Clear = 1,
  @CreatedByAgent = @CreatedByAgent_eaa2edb4,
  @CreatedByAgent_Clear = 1,
  @DateField = @DateField_eaa2edb4,
  @DateField_Clear = 1;

GO

-- Save MJ_BizApps_Sonar: Factors (core SP call only)
DECLARE @ID_e999d338 UNIQUEIDENTIFIER,
@Name_e999d338 NVARCHAR(200),
@Slug_e999d338 NVARCHAR(100),
@Description_e999d338 NVARCHAR(MAX),
@ScoreModelID_e999d338 UNIQUEIDENTIFIER,
@AnchorEntityID_e999d338 UNIQUEIDENTIFIER,
@FactorType_e999d338 NVARCHAR(20),
@SourceRelatedEntityID_e999d338 UNIQUEIDENTIFIER,
@SourceEntityID_e999d338 UNIQUEIDENTIFIER,
@FilterExpression_e999d338 NVARCHAR(MAX),
@Aggregation_e999d338 NVARCHAR(20),
@AggregateFieldName_e999d338 NVARCHAR(200),
@TimeWindowID_e999d338 UNIQUEIDENTIFIER,
@RecencyDecayHalfLifeDays_e999d338 INT,
@ActionID_e999d338 UNIQUEIDENTIFIER,
@ActionParamsJSON_e999d338 NVARCHAR(MAX),
@ExecutionMode_e999d338 NVARCHAR(12),
@IsExpensive_e999d338 BIT,
@MaxConcurrency_e999d338 INT,
@RateLimitPerMinute_e999d338 INT,
@CacheTTLSeconds_e999d338 INT,
@SourceScoreModelID_e999d338 UNIQUEIDENTIFIER,
@RawDataType_e999d338 NVARCHAR(12),
@NormalizationMethod_e999d338 NVARCHAR(20),
@NormalizationParamsJSON_e999d338 NVARCHAR(MAX),
@OutputMin_e999d338 DECIMAL(9, 4),
@OutputMax_e999d338 DECIMAL(9, 4),
@HigherIsBetter_e999d338 BIT,
@PromotionState_e999d338 NVARCHAR(20),
@LastValidatedAt_e999d338 DATETIME2,
@CreatedByAgent_e999d338 NVARCHAR(60),
@DateField_e999d338 NVARCHAR(200)
SET
  @ID_e999d338 = '4D09A1F1-44A7-524F-BFB6-576550070B5D'
SET
  @Name_e999d338 = N'Survey Participation'
SET
  @Slug_e999d338 = N'morecheese-survey-participation'
SET
  @Description_e999d338 = N'Surveys the member responded to over the last 24 months.'
SET
  @ScoreModelID_e999d338 = '05C13018-27B8-53DE-9D1D-129E6E15DF1C'
SET
  @AnchorEntityID_e999d338 = '7A94ADA9-7880-4FAE-97D8-DB0E934C3F5F'
SET
  @FactorType_e999d338 = N'Declarative'
SET
  @SourceRelatedEntityID_e999d338 = '73A51ECF-B377-53F4-BFCF-04A2F9C85C1A'
SET
  @SourceEntityID_e999d338 = '63600739-7165-4BDC-B7D7-19A1B1951DFA'
SET
  @Aggregation_e999d338 = N'Count'
SET
  @TimeWindowID_e999d338 = '97DF3796-A479-558E-9927-755A48D0D061'
SET
  @IsExpensive_e999d338 = 0
SET
  @NormalizationMethod_e999d338 = N'Percentile'
SET
  @HigherIsBetter_e999d338 = 1
SET
  @PromotionState_e999d338 = N'Approved'
SET
  @DateField_e999d338 = N'SubmittedAt' EXEC [__mj_BizAppsSonar].spCreateFactor @ID = @ID_e999d338,
  @Name = @Name_e999d338,
  @Slug = @Slug_e999d338,
  @Description = @Description_e999d338,
  @ScoreModelID = @ScoreModelID_e999d338,
  @AnchorEntityID = @AnchorEntityID_e999d338,
  @FactorType = @FactorType_e999d338,
  @SourceRelatedEntityID = @SourceRelatedEntityID_e999d338,
  @SourceEntityID = @SourceEntityID_e999d338,
  @FilterExpression = @FilterExpression_e999d338,
  @FilterExpression_Clear = 1,
  @Aggregation = @Aggregation_e999d338,
  @AggregateFieldName = @AggregateFieldName_e999d338,
  @AggregateFieldName_Clear = 1,
  @TimeWindowID = @TimeWindowID_e999d338,
  @RecencyDecayHalfLifeDays = @RecencyDecayHalfLifeDays_e999d338,
  @RecencyDecayHalfLifeDays_Clear = 1,
  @ActionID = @ActionID_e999d338,
  @ActionID_Clear = 1,
  @ActionParamsJSON = @ActionParamsJSON_e999d338,
  @ActionParamsJSON_Clear = 1,
  @ExecutionMode = @ExecutionMode_e999d338,
  @ExecutionMode_Clear = 1,
  @IsExpensive = @IsExpensive_e999d338,
  @MaxConcurrency = @MaxConcurrency_e999d338,
  @MaxConcurrency_Clear = 1,
  @RateLimitPerMinute = @RateLimitPerMinute_e999d338,
  @RateLimitPerMinute_Clear = 1,
  @CacheTTLSeconds = @CacheTTLSeconds_e999d338,
  @CacheTTLSeconds_Clear = 1,
  @SourceScoreModelID = @SourceScoreModelID_e999d338,
  @SourceScoreModelID_Clear = 1,
  @RawDataType = @RawDataType_e999d338,
  @RawDataType_Clear = 1,
  @NormalizationMethod = @NormalizationMethod_e999d338,
  @NormalizationParamsJSON = @NormalizationParamsJSON_e999d338,
  @NormalizationParamsJSON_Clear = 1,
  @OutputMin = @OutputMin_e999d338,
  @OutputMin_Clear = 1,
  @OutputMax = @OutputMax_e999d338,
  @OutputMax_Clear = 1,
  @HigherIsBetter = @HigherIsBetter_e999d338,
  @PromotionState = @PromotionState_e999d338,
  @LastValidatedAt = @LastValidatedAt_e999d338,
  @LastValidatedAt_Clear = 1,
  @CreatedByAgent = @CreatedByAgent_e999d338,
  @CreatedByAgent_Clear = 1,
  @DateField = @DateField_e999d338;

GO

-- Save MJ_BizApps_Sonar: Model Factors (core SP call only)
DECLARE @ID_e8b0a6ff UNIQUEIDENTIFIER,
@ScoreModelID_e8b0a6ff UNIQUEIDENTIFIER,
@FactorID_e8b0a6ff UNIQUEIDENTIFIER,
@Weight_e8b0a6ff DECIMAL(9, 4),
@WeightMode_e8b0a6ff NVARCHAR(12),
@ContributionCap_e8b0a6ff DECIMAL(9, 4),
@ContributionFloor_e8b0a6ff DECIMAL(9, 4),
@TrendWeight_e8b0a6ff DECIMAL(9, 4),
@MissingDataPolicy_e8b0a6ff NVARCHAR(16),
@IsRequired_e8b0a6ff BIT,
@DisplayLabel_e8b0a6ff NVARCHAR(200),
@DisplayOrder_e8b0a6ff INT
SET
  @ID_e8b0a6ff = 'C1D324B8-C8D5-59E5-8125-7E673B33E2F3'
SET
  @ScoreModelID_e8b0a6ff = '05C13018-27B8-53DE-9D1D-129E6E15DF1C'
SET
  @FactorID_e8b0a6ff = '83F3C3B5-D8DE-54DA-8969-BAA1D947D77B'
SET
  @Weight_e8b0a6ff = 3
SET
  @WeightMode_e8b0a6ff = N'Additive'
SET
  @MissingDataPolicy_e8b0a6ff = N'Zero'
SET
  @IsRequired_e8b0a6ff = 0
SET
  @DisplayLabel_e8b0a6ff = N'Event participation (12m)'
SET
  @DisplayOrder_e8b0a6ff = 1
EXEC [__mj_BizAppsSonar].spCreateModelFactor @ID = @ID_e8b0a6ff,
  @ScoreModelID = @ScoreModelID_e8b0a6ff,
  @FactorID = @FactorID_e8b0a6ff,
  @Weight = @Weight_e8b0a6ff,
  @WeightMode = @WeightMode_e8b0a6ff,
  @ContributionCap = @ContributionCap_e8b0a6ff,
  @ContributionCap_Clear = 1,
  @ContributionFloor = @ContributionFloor_e8b0a6ff,
  @ContributionFloor_Clear = 1,
  @TrendWeight = @TrendWeight_e8b0a6ff,
  @TrendWeight_Clear = 1,
  @MissingDataPolicy = @MissingDataPolicy_e8b0a6ff,
  @IsRequired = @IsRequired_e8b0a6ff,
  @DisplayLabel = @DisplayLabel_e8b0a6ff,
  @DisplayOrder = @DisplayOrder_e8b0a6ff;

GO

-- Save MJ_BizApps_Sonar: Model Factors (core SP call only)
DECLARE @ID_5d5842df UNIQUEIDENTIFIER,
@ScoreModelID_5d5842df UNIQUEIDENTIFIER,
@FactorID_5d5842df UNIQUEIDENTIFIER,
@Weight_5d5842df DECIMAL(9, 4),
@WeightMode_5d5842df NVARCHAR(12),
@ContributionCap_5d5842df DECIMAL(9, 4),
@ContributionFloor_5d5842df DECIMAL(9, 4),
@TrendWeight_5d5842df DECIMAL(9, 4),
@MissingDataPolicy_5d5842df NVARCHAR(16),
@IsRequired_5d5842df BIT,
@DisplayLabel_5d5842df NVARCHAR(200),
@DisplayOrder_5d5842df INT
SET
  @ID_5d5842df = '87AC52AD-B6C5-52B9-925E-37436418C6EB'
SET
  @ScoreModelID_5d5842df = '05C13018-27B8-53DE-9D1D-129E6E15DF1C'
SET
  @FactorID_5d5842df = '570029BF-9C80-5C72-9914-E99D12C338B1'
SET
  @Weight_5d5842df = 3
SET
  @WeightMode_5d5842df = N'Additive'
SET
  @MissingDataPolicy_5d5842df = N'Zero'
SET
  @IsRequired_5d5842df = 0
SET
  @DisplayLabel_5d5842df = N'Committee service'
SET
  @DisplayOrder_5d5842df = 2
EXEC [__mj_BizAppsSonar].spCreateModelFactor @ID = @ID_5d5842df,
  @ScoreModelID = @ScoreModelID_5d5842df,
  @FactorID = @FactorID_5d5842df,
  @Weight = @Weight_5d5842df,
  @WeightMode = @WeightMode_5d5842df,
  @ContributionCap = @ContributionCap_5d5842df,
  @ContributionCap_Clear = 1,
  @ContributionFloor = @ContributionFloor_5d5842df,
  @ContributionFloor_Clear = 1,
  @TrendWeight = @TrendWeight_5d5842df,
  @TrendWeight_Clear = 1,
  @MissingDataPolicy = @MissingDataPolicy_5d5842df,
  @IsRequired = @IsRequired_5d5842df,
  @DisplayLabel = @DisplayLabel_5d5842df,
  @DisplayOrder = @DisplayOrder_5d5842df;

GO

-- Save MJ_BizApps_Sonar: Model Factors (core SP call only)
DECLARE @ID_adb5d47c UNIQUEIDENTIFIER,
@ScoreModelID_adb5d47c UNIQUEIDENTIFIER,
@FactorID_adb5d47c UNIQUEIDENTIFIER,
@Weight_adb5d47c DECIMAL(9, 4),
@WeightMode_adb5d47c NVARCHAR(12),
@ContributionCap_adb5d47c DECIMAL(9, 4),
@ContributionFloor_adb5d47c DECIMAL(9, 4),
@TrendWeight_adb5d47c DECIMAL(9, 4),
@MissingDataPolicy_adb5d47c NVARCHAR(16),
@IsRequired_adb5d47c BIT,
@DisplayLabel_adb5d47c NVARCHAR(200),
@DisplayOrder_adb5d47c INT
SET
  @ID_adb5d47c = '170A62A8-6880-5AF3-8BA2-9A6B122DD9E9'
SET
  @ScoreModelID_adb5d47c = '05C13018-27B8-53DE-9D1D-129E6E15DF1C'
SET
  @FactorID_adb5d47c = '7A2C147C-A4DB-5DAD-AB01-A99344A4AA82'
SET
  @Weight_adb5d47c = 3
SET
  @WeightMode_adb5d47c = N'Additive'
SET
  @MissingDataPolicy_adb5d47c = N'Zero'
SET
  @IsRequired_adb5d47c = 0
SET
  @DisplayLabel_adb5d47c = N'Certifications'
SET
  @DisplayOrder_adb5d47c = 3
EXEC [__mj_BizAppsSonar].spCreateModelFactor @ID = @ID_adb5d47c,
  @ScoreModelID = @ScoreModelID_adb5d47c,
  @FactorID = @FactorID_adb5d47c,
  @Weight = @Weight_adb5d47c,
  @WeightMode = @WeightMode_adb5d47c,
  @ContributionCap = @ContributionCap_adb5d47c,
  @ContributionCap_Clear = 1,
  @ContributionFloor = @ContributionFloor_adb5d47c,
  @ContributionFloor_Clear = 1,
  @TrendWeight = @TrendWeight_adb5d47c,
  @TrendWeight_Clear = 1,
  @MissingDataPolicy = @MissingDataPolicy_adb5d47c,
  @IsRequired = @IsRequired_adb5d47c,
  @DisplayLabel = @DisplayLabel_adb5d47c,
  @DisplayOrder = @DisplayOrder_adb5d47c;

GO

-- Save MJ_BizApps_Sonar: Model Factors (core SP call only)
DECLARE @ID_d241f049 UNIQUEIDENTIFIER,
@ScoreModelID_d241f049 UNIQUEIDENTIFIER,
@FactorID_d241f049 UNIQUEIDENTIFIER,
@Weight_d241f049 DECIMAL(9, 4),
@WeightMode_d241f049 NVARCHAR(12),
@ContributionCap_d241f049 DECIMAL(9, 4),
@ContributionFloor_d241f049 DECIMAL(9, 4),
@TrendWeight_d241f049 DECIMAL(9, 4),
@MissingDataPolicy_d241f049 NVARCHAR(16),
@IsRequired_d241f049 BIT,
@DisplayLabel_d241f049 NVARCHAR(200),
@DisplayOrder_d241f049 INT
SET
  @ID_d241f049 = '5750EE23-F7AA-516B-A2CE-C59476FBA6B4'
SET
  @ScoreModelID_d241f049 = '05C13018-27B8-53DE-9D1D-129E6E15DF1C'
SET
  @FactorID_d241f049 = '9DD8C3C8-7F39-5058-A8BA-D830EA41832D'
SET
  @Weight_d241f049 = 2
SET
  @WeightMode_d241f049 = N'Additive'
SET
  @MissingDataPolicy_d241f049 = N'Zero'
SET
  @IsRequired_d241f049 = 0
SET
  @DisplayLabel_d241f049 = N'Learning activity (12m)'
SET
  @DisplayOrder_d241f049 = 4
EXEC [__mj_BizAppsSonar].spCreateModelFactor @ID = @ID_d241f049,
  @ScoreModelID = @ScoreModelID_d241f049,
  @FactorID = @FactorID_d241f049,
  @Weight = @Weight_d241f049,
  @WeightMode = @WeightMode_d241f049,
  @ContributionCap = @ContributionCap_d241f049,
  @ContributionCap_Clear = 1,
  @ContributionFloor = @ContributionFloor_d241f049,
  @ContributionFloor_Clear = 1,
  @TrendWeight = @TrendWeight_d241f049,
  @TrendWeight_Clear = 1,
  @MissingDataPolicy = @MissingDataPolicy_d241f049,
  @IsRequired = @IsRequired_d241f049,
  @DisplayLabel = @DisplayLabel_d241f049,
  @DisplayOrder = @DisplayOrder_d241f049;

GO

-- Save MJ_BizApps_Sonar: Model Factors (core SP call only)
DECLARE @ID_8e485ad0 UNIQUEIDENTIFIER,
@ScoreModelID_8e485ad0 UNIQUEIDENTIFIER,
@FactorID_8e485ad0 UNIQUEIDENTIFIER,
@Weight_8e485ad0 DECIMAL(9, 4),
@WeightMode_8e485ad0 NVARCHAR(12),
@ContributionCap_8e485ad0 DECIMAL(9, 4),
@ContributionFloor_8e485ad0 DECIMAL(9, 4),
@TrendWeight_8e485ad0 DECIMAL(9, 4),
@MissingDataPolicy_8e485ad0 NVARCHAR(16),
@IsRequired_8e485ad0 BIT,
@DisplayLabel_8e485ad0 NVARCHAR(200),
@DisplayOrder_8e485ad0 INT
SET
  @ID_8e485ad0 = '9526CD7C-9BD4-55D4-9C5D-9F17DD225119'
SET
  @ScoreModelID_8e485ad0 = '05C13018-27B8-53DE-9D1D-129E6E15DF1C'
SET
  @FactorID_8e485ad0 = '1A860AAD-8767-5E2A-9ECE-C359C3D4EC1F'
SET
  @Weight_8e485ad0 = 2
SET
  @WeightMode_8e485ad0 = N'Additive'
SET
  @MissingDataPolicy_8e485ad0 = N'Zero'
SET
  @IsRequired_8e485ad0 = 0
SET
  @DisplayLabel_8e485ad0 = N'Advocacy (24m)'
SET
  @DisplayOrder_8e485ad0 = 5
EXEC [__mj_BizAppsSonar].spCreateModelFactor @ID = @ID_8e485ad0,
  @ScoreModelID = @ScoreModelID_8e485ad0,
  @FactorID = @FactorID_8e485ad0,
  @Weight = @Weight_8e485ad0,
  @WeightMode = @WeightMode_8e485ad0,
  @ContributionCap = @ContributionCap_8e485ad0,
  @ContributionCap_Clear = 1,
  @ContributionFloor = @ContributionFloor_8e485ad0,
  @ContributionFloor_Clear = 1,
  @TrendWeight = @TrendWeight_8e485ad0,
  @TrendWeight_Clear = 1,
  @MissingDataPolicy = @MissingDataPolicy_8e485ad0,
  @IsRequired = @IsRequired_8e485ad0,
  @DisplayLabel = @DisplayLabel_8e485ad0,
  @DisplayOrder = @DisplayOrder_8e485ad0;

GO

-- Save MJ_BizApps_Sonar: Model Factors (core SP call only)
DECLARE @ID_e77f765c UNIQUEIDENTIFIER,
@ScoreModelID_e77f765c UNIQUEIDENTIFIER,
@FactorID_e77f765c UNIQUEIDENTIFIER,
@Weight_e77f765c DECIMAL(9, 4),
@WeightMode_e77f765c NVARCHAR(12),
@ContributionCap_e77f765c DECIMAL(9, 4),
@ContributionFloor_e77f765c DECIMAL(9, 4),
@TrendWeight_e77f765c DECIMAL(9, 4),
@MissingDataPolicy_e77f765c NVARCHAR(16),
@IsRequired_e77f765c BIT,
@DisplayLabel_e77f765c NVARCHAR(200),
@DisplayOrder_e77f765c INT
SET
  @ID_e77f765c = '3DC0231E-D0E6-5B08-B3E0-0F7A030031B2'
SET
  @ScoreModelID_e77f765c = '05C13018-27B8-53DE-9D1D-129E6E15DF1C'
SET
  @FactorID_e77f765c = 'EC18FBE8-6AA4-5FF4-BAE7-7B2AD248EA49'
SET
  @Weight_e77f765c = 2
SET
  @WeightMode_e77f765c = N'Additive'
SET
  @MissingDataPolicy_e77f765c = N'Zero'
SET
  @IsRequired_e77f765c = 0
SET
  @DisplayLabel_e77f765c = N'Competition entries'
SET
  @DisplayOrder_e77f765c = 6
EXEC [__mj_BizAppsSonar].spCreateModelFactor @ID = @ID_e77f765c,
  @ScoreModelID = @ScoreModelID_e77f765c,
  @FactorID = @FactorID_e77f765c,
  @Weight = @Weight_e77f765c,
  @WeightMode = @WeightMode_e77f765c,
  @ContributionCap = @ContributionCap_e77f765c,
  @ContributionCap_Clear = 1,
  @ContributionFloor = @ContributionFloor_e77f765c,
  @ContributionFloor_Clear = 1,
  @TrendWeight = @TrendWeight_e77f765c,
  @TrendWeight_Clear = 1,
  @MissingDataPolicy = @MissingDataPolicy_e77f765c,
  @IsRequired = @IsRequired_e77f765c,
  @DisplayLabel = @DisplayLabel_e77f765c,
  @DisplayOrder = @DisplayOrder_e77f765c;

GO

-- Save MJ_BizApps_Sonar: Model Factors (core SP call only)
DECLARE @ID_98f5b5be UNIQUEIDENTIFIER,
@ScoreModelID_98f5b5be UNIQUEIDENTIFIER,
@FactorID_98f5b5be UNIQUEIDENTIFIER,
@Weight_98f5b5be DECIMAL(9, 4),
@WeightMode_98f5b5be NVARCHAR(12),
@ContributionCap_98f5b5be DECIMAL(9, 4),
@ContributionFloor_98f5b5be DECIMAL(9, 4),
@TrendWeight_98f5b5be DECIMAL(9, 4),
@MissingDataPolicy_98f5b5be NVARCHAR(16),
@IsRequired_98f5b5be BIT,
@DisplayLabel_98f5b5be NVARCHAR(200),
@DisplayOrder_98f5b5be INT
SET
  @ID_98f5b5be = 'C7264C81-78B5-5C93-9578-261010FCEDAB'
SET
  @ScoreModelID_98f5b5be = '05C13018-27B8-53DE-9D1D-129E6E15DF1C'
SET
  @FactorID_98f5b5be = '2C7B495A-61FE-553A-B219-B5F576E23278'
SET
  @Weight_98f5b5be = 2
SET
  @WeightMode_98f5b5be = N'Additive'
SET
  @MissingDataPolicy_98f5b5be = N'Zero'
SET
  @IsRequired_98f5b5be = 0
SET
  @DisplayLabel_98f5b5be = N'Event recency'
SET
  @DisplayOrder_98f5b5be = 7
EXEC [__mj_BizAppsSonar].spCreateModelFactor @ID = @ID_98f5b5be,
  @ScoreModelID = @ScoreModelID_98f5b5be,
  @FactorID = @FactorID_98f5b5be,
  @Weight = @Weight_98f5b5be,
  @WeightMode = @WeightMode_98f5b5be,
  @ContributionCap = @ContributionCap_98f5b5be,
  @ContributionCap_Clear = 1,
  @ContributionFloor = @ContributionFloor_98f5b5be,
  @ContributionFloor_Clear = 1,
  @TrendWeight = @TrendWeight_98f5b5be,
  @TrendWeight_Clear = 1,
  @MissingDataPolicy = @MissingDataPolicy_98f5b5be,
  @IsRequired = @IsRequired_98f5b5be,
  @DisplayLabel = @DisplayLabel_98f5b5be,
  @DisplayOrder = @DisplayOrder_98f5b5be;

GO

-- Save MJ_BizApps_Sonar: Model Factors (core SP call only)
DECLARE @ID_7cf63544 UNIQUEIDENTIFIER,
@ScoreModelID_7cf63544 UNIQUEIDENTIFIER,
@FactorID_7cf63544 UNIQUEIDENTIFIER,
@Weight_7cf63544 DECIMAL(9, 4),
@WeightMode_7cf63544 NVARCHAR(12),
@ContributionCap_7cf63544 DECIMAL(9, 4),
@ContributionFloor_7cf63544 DECIMAL(9, 4),
@TrendWeight_7cf63544 DECIMAL(9, 4),
@MissingDataPolicy_7cf63544 NVARCHAR(16),
@IsRequired_7cf63544 BIT,
@DisplayLabel_7cf63544 NVARCHAR(200),
@DisplayOrder_7cf63544 INT
SET
  @ID_7cf63544 = '65EDE704-8EF3-58F1-B1B7-F03972020947'
SET
  @ScoreModelID_7cf63544 = '05C13018-27B8-53DE-9D1D-129E6E15DF1C'
SET
  @FactorID_7cf63544 = '4D09A1F1-44A7-524F-BFB6-576550070B5D'
SET
  @Weight_7cf63544 = 1
SET
  @WeightMode_7cf63544 = N'Additive'
SET
  @MissingDataPolicy_7cf63544 = N'Zero'
SET
  @IsRequired_7cf63544 = 0
SET
  @DisplayLabel_7cf63544 = N'Survey participation (24m)'
SET
  @DisplayOrder_7cf63544 = 8
EXEC [__mj_BizAppsSonar].spCreateModelFactor @ID = @ID_7cf63544,
  @ScoreModelID = @ScoreModelID_7cf63544,
  @FactorID = @FactorID_7cf63544,
  @Weight = @Weight_7cf63544,
  @WeightMode = @WeightMode_7cf63544,
  @ContributionCap = @ContributionCap_7cf63544,
  @ContributionCap_Clear = 1,
  @ContributionFloor = @ContributionFloor_7cf63544,
  @ContributionFloor_Clear = 1,
  @TrendWeight = @TrendWeight_7cf63544,
  @TrendWeight_Clear = 1,
  @MissingDataPolicy = @MissingDataPolicy_7cf63544,
  @IsRequired = @IsRequired_7cf63544,
  @DisplayLabel = @DisplayLabel_7cf63544,
  @DisplayOrder = @DisplayOrder_7cf63544;

GO

-- Save MJ_BizApps_Sonar: Score Models (core SP call only)
DECLARE @Name_e46eae96 NVARCHAR(200),
@Slug_e46eae96 NVARCHAR(100),
@Description_e46eae96 NVARCHAR(MAX),
@AnchorEntityID_e46eae96 UNIQUEIDENTIFIER,
@Status_e46eae96 NVARCHAR(20),
@CurrentVersionID_e46eae96 UNIQUEIDENTIFIER,
@ScoreScaleMin_e46eae96 DECIMAL(9, 4),
@ScoreScaleMax_e46eae96 DECIMAL(9, 4),
@CombineStrategy_e46eae96 NVARCHAR(30),
@CombineExpression_e46eae96 NVARCHAR(MAX),
@BandSetID_e46eae96 UNIQUEIDENTIFIER,
@PopulationFilter_e46eae96 NVARCHAR(MAX),
@RecomputeMode_e46eae96 NVARCHAR(20),
@RecomputeCron_e46eae96 NVARCHAR(100),
@AsOfStrategy_e46eae96 NVARCHAR(20),
@IsCalibrated_e46eae96 BIT,
@TrendWindowDays_e46eae96 INT,
@OwnerUserID_e46eae96 UNIQUEIDENTIFIER,
@EffectiveFrom_e46eae96 DATETIME2,
@EffectiveTo_e46eae96 DATETIME2,
@Notes_e46eae96 NVARCHAR(MAX),
@ID_e46eae96 UNIQUEIDENTIFIER
SET
  @Name_e46eae96 = N'Member Engagement Score'
SET
  @Slug_e46eae96 = N'morecheese-engagement'
SET
  @Description_e46eae96 = N'Composite engagement score for federation members — breadth, recency, and depth of participation across events, governance, learning, advocacy, surveys, certifications, and competitions. The retention early-warning dial, computed live by Sonar.'
SET
  @AnchorEntityID_e46eae96 = '7A94ADA9-7880-4FAE-97D8-DB0E934C3F5F'
SET
  @Status_e46eae96 = N'Active'
SET
  @CurrentVersionID_e46eae96 = '9EC51FE5-B002-564E-9C7E-7B8E4954CC5B'
SET
  @ScoreScaleMin_e46eae96 = 0
SET
  @ScoreScaleMax_e46eae96 = 100
SET
  @CombineStrategy_e46eae96 = N'WeightedSum'
SET
  @BandSetID_e46eae96 = '82A80C88-CF9D-5386-A3C5-8ACDE3025B55'
SET
  @RecomputeMode_e46eae96 = N'Scheduled'
SET
  @AsOfStrategy_e46eae96 = N'RunTime'
SET
  @IsCalibrated_e46eae96 = 0
SET
  @OwnerUserID_e46eae96 = 'C6309AFC-F5DE-5794-8865-FC99D5DD82F4'
SET
  @EffectiveFrom_e46eae96 = '2025-10-04T10:00:00.000Z'
SET
  @ID_e46eae96 = '05C13018-27B8-53DE-9D1D-129E6E15DF1C' EXEC [__mj_BizAppsSonar].spUpdateScoreModel @Name = @Name_e46eae96,
  @Slug = @Slug_e46eae96,
  @Description = @Description_e46eae96,
  @AnchorEntityID = @AnchorEntityID_e46eae96,
  @Status = @Status_e46eae96,
  @CurrentVersionID = @CurrentVersionID_e46eae96,
  @ScoreScaleMin = @ScoreScaleMin_e46eae96,
  @ScoreScaleMax = @ScoreScaleMax_e46eae96,
  @CombineStrategy = @CombineStrategy_e46eae96,
  @CombineExpression = @CombineExpression_e46eae96,
  @CombineExpression_Clear = 1,
  @BandSetID = @BandSetID_e46eae96,
  @PopulationFilter = @PopulationFilter_e46eae96,
  @PopulationFilter_Clear = 1,
  @RecomputeMode = @RecomputeMode_e46eae96,
  @RecomputeCron = @RecomputeCron_e46eae96,
  @RecomputeCron_Clear = 1,
  @AsOfStrategy = @AsOfStrategy_e46eae96,
  @IsCalibrated = @IsCalibrated_e46eae96,
  @TrendWindowDays = @TrendWindowDays_e46eae96,
  @TrendWindowDays_Clear = 1,
  @OwnerUserID = @OwnerUserID_e46eae96,
  @EffectiveFrom = @EffectiveFrom_e46eae96,
  @EffectiveTo = @EffectiveTo_e46eae96,
  @EffectiveTo_Clear = 1,
  @Notes = @Notes_e46eae96,
  @Notes_Clear = 1,
  @ID = @ID_e46eae96;

GO


-- End of SQL Logging Session
-- Session ID: 76142961-c3e5-4417-95a1-cb738e37021f
-- Completed: 2026-07-27T17:05:44.646Z
-- Duration: 894ms
-- Total Statements: 34
