-- SQL Logging Session
-- Session ID: 3c3f3988-1285-43d3-b9e5-8ad98bc776f9
-- Started: 2026-07-27T18:40:41.638Z
-- Description: MetadataSync push operation
-- Format: Migration-ready with Flyway schema placeholders
-- Generated by MemberJunction

-- Save MJ: AI Vendors (core SP call only)
DECLARE @ID_bc0d2ba1 UNIQUEIDENTIFIER,
@Name_bc0d2ba1 NVARCHAR(50),
@Description_bc0d2ba1 NVARCHAR(MAX),
@CredentialTypeID_bc0d2ba1 UNIQUEIDENTIFIER
SET
  @ID_bc0d2ba1 = 'EB93BD78-D94F-5EB4-A88D-7B73DA2C8B6F'
SET
  @Name_bc0d2ba1 = N'rasa.io'
SET
  @Description_bc0d2ba1 = N'rasa.io — provider of Betty, the association-trained assistant used by the International Cheese Federation demo.' EXEC [${flyway:defaultSchema}].spCreateAIVendor @ID = @ID_bc0d2ba1,
  @Name = @Name_bc0d2ba1,
  @Description = @Description_bc0d2ba1,
  @CredentialTypeID = @CredentialTypeID_bc0d2ba1,
  @CredentialTypeID_Clear = 1;

GO

-- Save MJ: AI Models (core SP call only)
DECLARE @ID_e96eca61 UNIQUEIDENTIFIER,
@Name_e96eca61 NVARCHAR(50),
@Description_e96eca61 NVARCHAR(MAX),
@AIModelTypeID_e96eca61 UNIQUEIDENTIFIER,
@PowerRank_e96eca61 INT,
@IsActive_e96eca61 BIT,
@SpeedRank_e96eca61 INT,
@CostRank_e96eca61 INT,
@ModelSelectionInsights_e96eca61 NVARCHAR(MAX),
@InheritTypeModalities_e96eca61 BIT,
@PriorVersionID_e96eca61 UNIQUEIDENTIFIER,
@SupportsPrefill_e96eca61 BIT,
@PrefillFallbackText_e96eca61 NVARCHAR(MAX)
SET
  @ID_e96eca61 = 'D6B3CFD1-6C41-5A26-B89F-54C875097FA6'
SET
  @Name_e96eca61 = N'Betty'
SET
  @Description_e96eca61 = N'Association-trained retrieval assistant (rasa.io). Answers member questions grounded in the federation''s published knowledge base.'
SET
  @AIModelTypeID_e96eca61 = 'E8A5CCEC-6A37-EF11-86D4-000D3A4E707E'
SET
  @PowerRank_e96eca61 = 0
SET
  @IsActive_e96eca61 = 1
SET
  @SpeedRank_e96eca61 = 0
SET
  @CostRank_e96eca61 = 0
SET
  @InheritTypeModalities_e96eca61 = 1
EXEC [${flyway:defaultSchema}].spCreateAIModel @ID = @ID_e96eca61,
  @Name = @Name_e96eca61,
  @Description = @Description_e96eca61,
  @AIModelTypeID = @AIModelTypeID_e96eca61,
  @PowerRank = @PowerRank_e96eca61,
  @IsActive = @IsActive_e96eca61,
  @SpeedRank = @SpeedRank_e96eca61,
  @CostRank = @CostRank_e96eca61,
  @ModelSelectionInsights = @ModelSelectionInsights_e96eca61,
  @ModelSelectionInsights_Clear = 1,
  @InheritTypeModalities = @InheritTypeModalities_e96eca61,
  @PriorVersionID = @PriorVersionID_e96eca61,
  @PriorVersionID_Clear = 1,
  @SupportsPrefill = @SupportsPrefill_e96eca61,
  @SupportsPrefill_Clear = 1,
  @PrefillFallbackText = @PrefillFallbackText_e96eca61,
  @PrefillFallbackText_Clear = 1;

GO

-- Save MJ: AI Model Vendors (core SP call only)
DECLARE @ID_546f692e UNIQUEIDENTIFIER,
@ModelID_546f692e UNIQUEIDENTIFIER,
@VendorID_546f692e UNIQUEIDENTIFIER,
@Priority_546f692e INT,
@Status_546f692e NVARCHAR(20),
@DriverClass_546f692e NVARCHAR(100),
@DriverImportPath_546f692e NVARCHAR(255),
@APIName_546f692e NVARCHAR(100),
@MaxInputTokens_546f692e INT,
@MaxOutputTokens_546f692e INT,
@SupportedResponseFormats_546f692e NVARCHAR(100),
@SupportsEffortLevel_546f692e BIT,
@SupportsStreaming_546f692e BIT,
@TypeID_546f692e UNIQUEIDENTIFIER,
@SupportsPrefill_546f692e BIT,
@PrefillFallbackText_546f692e NVARCHAR(MAX)
SET
  @ID_546f692e = '832E6ECA-62AC-57AA-B6D8-9408A37E3084'
SET
  @ModelID_546f692e = 'D6B3CFD1-6C41-5A26-B89F-54C875097FA6'
SET
  @VendorID_546f692e = 'EB93BD78-D94F-5EB4-A88D-7B73DA2C8B6F'
SET
  @Priority_546f692e = 0
SET
  @Status_546f692e = N'Active'
SET
  @DriverClass_546f692e = N'BettyBotLLM'
SET
  @APIName_546f692e = N'default'
SET
  @SupportedResponseFormats_546f692e = N'Any'
SET
  @SupportsEffortLevel_546f692e = 0
SET
  @SupportsStreaming_546f692e = 0
SET
  @TypeID_546f692e = '5B043EC3-1FF2-4730-B5D2-7CFDA50979B3' EXEC [${flyway:defaultSchema}].spCreateAIModelVendor @ID = @ID_546f692e,
  @ModelID = @ModelID_546f692e,
  @VendorID = @VendorID_546f692e,
  @Priority = @Priority_546f692e,
  @Status = @Status_546f692e,
  @DriverClass = @DriverClass_546f692e,
  @DriverImportPath = @DriverImportPath_546f692e,
  @DriverImportPath_Clear = 1,
  @APIName = @APIName_546f692e,
  @MaxInputTokens = @MaxInputTokens_546f692e,
  @MaxInputTokens_Clear = 1,
  @MaxOutputTokens = @MaxOutputTokens_546f692e,
  @MaxOutputTokens_Clear = 1,
  @SupportedResponseFormats = @SupportedResponseFormats_546f692e,
  @SupportsEffortLevel = @SupportsEffortLevel_546f692e,
  @SupportsStreaming = @SupportsStreaming_546f692e,
  @TypeID = @TypeID_546f692e,
  @SupportsPrefill = @SupportsPrefill_546f692e,
  @SupportsPrefill_Clear = 1,
  @PrefillFallbackText = @PrefillFallbackText_546f692e,
  @PrefillFallbackText_Clear = 1;

GO


-- End of SQL Logging Session
-- Session ID: 3c3f3988-1285-43d3-b9e5-8ad98bc776f9
-- Completed: 2026-07-27T18:40:42.766Z
-- Duration: 1128ms
-- Total Statements: 3
