/**
 * Spec for the sync ID parity gate.
 *
 * The gate asserts that the Metadata_Sync migrations insert EXACTLY the primary keys sitting in
 * `generated/` for every loom-classified directory — no key in the tree that the seed forgets, no key
 * in the seed that the tree no longer has. A seed is regenerated by hand from one developer's
 * database, so it drifts from the tree the moment a record is added and the seed is not recut, and
 * nothing else in the repo compares the two.
 *
 * The gate is one top-level program with no exported seam; it reads `process.cwd()`. So each case
 * builds a throwaway repo root — a tiny tree and a tiny seed — and runs the CLI against it, which
 * also covers the exit status. Reading the real tree instead would prove only that today is fine.
 */
import { test, after } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const GATE = path.join(HERE, 'check-sync-id-parity.mjs');

const roots = [];
after(() => {
    for (const root of roots) fs.rmSync(root, { recursive: true, force: true });
});

const ID_A = 'AAAAAAAA-1111-2222-3333-444444444444';
const ID_B = 'BBBBBBBB-1111-2222-3333-444444444444';
const ENTITY = 'MoreCheese: People';

/**
 * A throwaway repo root.
 *
 * `dirs` maps a loom directory to `{ entity, records }`, where each record is the `primaryKey` object
 * as `generated/` writes it. `seed` is the Metadata_Sync SQL; pass `null` for a repo with none.
 */
function fixture({ dirs = {}, seed = '' } = {}) {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'sync-id-parity-'));
    roots.push(root);
    fs.mkdirSync(path.join(root, 'data'), { recursive: true });
    fs.mkdirSync(path.join(root, 'migrations'), { recursive: true });

    const directories = {};
    for (const [dir, { entity, records, omitSyncConfig }] of Object.entries(dirs)) {
        directories[dir] = { tier: 'generated', classification: 'loom', reason: 'Loom-generated' };
        const folder = path.join(root, 'generated', dir);
        fs.mkdirSync(folder, { recursive: true });
        if (!omitSyncConfig) {
            fs.writeFileSync(path.join(folder, '.mj-sync.json'), JSON.stringify({ entity }));
        }
        fs.writeFileSync(
            path.join(folder, `.${dir}.json`),
            JSON.stringify(records.map((primaryKey) => ({ primaryKey, fields: { Name: 'x' } })), null, 2),
        );
    }
    fs.writeFileSync(path.join(root, 'data/ownership.json'), JSON.stringify({ version: 1, directories }));
    if (seed !== null) {
        fs.writeFileSync(path.join(root, 'migrations/V202609190000__v1.2.0__Metadata_Sync_Part1of1.sql'), seed);
    }
    return root;
}

/**
 * One `-- Save` block per key, in the shape CodeGen actually emits: a DECLARE, a `SET` whose value
 * line carries the `EXEC` on its tail, and a `GO`. The gate's parser is written against that shape,
 * so a fixture in a tidier shape would test a parser this repo does not have.
 */
function saveBlocks(entity, keys) {
    return keys
        .map((pk, i) => {
            const suffix = `a${i}`;
            const fields = Object.entries(pk);
            const declares = fields.map(([f]) => `@${f}_${suffix} SQL_VARIANT`).join(',\n');
            const sets = fields
                .slice(0, -1)
                .map(([f, v]) => `SET\n  @${f}_${suffix} = ${typeof v === 'number' ? v : `N'${v}'`}`)
                .join('\n');
            const [lastField, lastValue] = fields[fields.length - 1];
            const args = fields.map(([f]) => `@${f} = @${f}_${suffix}`).join(',\n  ');
            return (
                `-- Save ${entity} (core SP call only)\n` +
                `DECLARE ${declares}\n` +
                (sets ? `${sets}\n` : '') +
                `SET\n  @${lastField}_${suffix} = ${typeof lastValue === 'number' ? lastValue : `N'${lastValue}'`} ` +
                `EXEC [\${mjSchema}].spCreateThing ${args};\n\nGO\n`
            );
        })
        .join('\n');
}

function runGate(root) {
    return spawnSync(process.execPath, [GATE], { cwd: root, encoding: 'utf8' });
}

// ── The rejection this gate exists for ──────────────────────────────────────────────────────────

test('a key in generated/ that the seed never names is a violation', () => {
    const root = fixture({
        dirs: { people: { entity: ENTITY, records: [{ ID: ID_A }, { ID: ID_B }] } },
        seed: saveBlocks(ENTITY, [{ ID: ID_A }]),
    });
    const run = runGate(root);
    assert.equal(run.status, 1);
    assert.match(run.stderr, /people \(MoreCheese: People\): generated=2 inserted=1 extra=0 missing=1/);
    assert.match(run.stderr, /Sync ID parity failed for 1 loom directory/);
});

test('the violation samples the missing key so it can be found', () => {
    const root = fixture({
        dirs: { people: { entity: ENTITY, records: [{ ID: ID_A }, { ID: ID_B }] } },
        seed: saveBlocks(ENTITY, [{ ID: ID_A }]),
    });
    assert.match(runGate(root).stderr, new RegExp(`missing sample: ID=${ID_B}`));
});

// The mirror: a seed cut before a record was deleted from the tree inserts a row nothing owns.
test('a key the seed names that generated/ no longer holds is a violation', () => {
    const root = fixture({
        dirs: { people: { entity: ENTITY, records: [{ ID: ID_A }] } },
        seed: saveBlocks(ENTITY, [{ ID: ID_A }, { ID: ID_B }]),
    });
    const run = runGate(root);
    assert.equal(run.status, 1);
    assert.match(run.stderr, /generated=1 inserted=2 extra=1 missing=0/);
});

// ── The states that are failures rather than nothing-to-check ───────────────────────────────────

// A directory that yields no keys at all reads as "parity holds" to any check that compares sets,
// which is exactly how a tree that stopped being parsed would report green.
test('a loom directory with no primary keys at all is a violation', () => {
    const root = fixture({ dirs: { people: { entity: ENTITY, records: [] } }, seed: saveBlocks(ENTITY, [{ ID: ID_A }]) });
    const run = runGate(root);
    assert.equal(run.status, 1);
    assert.match(run.stderr, /people \(MoreCheese: People\): zero primary keys in generated\//);
});

test('a loom directory with no .mj-sync.json entity is a violation', () => {
    const root = fixture({
        dirs: { people: { entity: ENTITY, records: [{ ID: ID_A }], omitSyncConfig: true } },
        seed: saveBlocks(ENTITY, [{ ID: ID_A }]),
    });
    const run = runGate(root);
    assert.equal(run.status, 1);
    assert.match(run.stderr, /people: missing generated\/people\/\.mj-sync\.json entity/);
});

test('a repo with no Metadata_Sync migration fails rather than passing over nothing', () => {
    const root = fixture({ dirs: { people: { entity: ENTITY, records: [{ ID: ID_A }] } }, seed: null });
    const run = runGate(root);
    assert.equal(run.status, 1);
    assert.match(run.stderr, /No Metadata_Sync migration files in migrations\//);
});

// ── Parity as the gate defines it ───────────────────────────────────────────────────────────────

test('a seed naming exactly the keys in its loom directory passes', () => {
    const root = fixture({
        dirs: { people: { entity: ENTITY, records: [{ ID: ID_A }, { ID: ID_B }] } },
        seed: saveBlocks(ENTITY, [{ ID: ID_A }, { ID: ID_B }]),
    });
    const run = runGate(root);
    assert.equal(run.status, 0, run.stderr);
    assert.match(run.stdout, /✓ people \(MoreCheese: People\): 2 keys \[ID\]/);
    assert.match(run.stdout, /inserted ID sets match generated\/ for every loom directory/);
});

// Shipped SQL writes ids in whichever case CodeGen felt like; the database does not care, and the
// gate normalises rather than reporting a phantom mismatch.
test('id casing does not decide parity', () => {
    const root = fixture({
        dirs: { people: { entity: ENTITY, records: [{ ID: ID_A }] } },
        seed: saveBlocks(ENTITY, [{ ID: ID_A.toLowerCase() }]),
    });
    assert.equal(runGate(root).status, 0);
});

// Not every entity is keyed on ID alone, and a gate that compared only ID would call two rows of a
// composite-keyed entity the same row.
test('every field of a composite primary key has to match', () => {
    const composite = { ID: ID_A, Sequence: 2 };
    const matching = fixture({
        dirs: { links: { entity: 'MoreCheese: Links', records: [composite] } },
        seed: saveBlocks('MoreCheese: Links', [composite]),
    });
    assert.equal(runGate(matching).status, 0, runGate(matching).stderr);

    const drifted = fixture({
        dirs: { links: { entity: 'MoreCheese: Links', records: [composite] } },
        seed: saveBlocks('MoreCheese: Links', [{ ID: ID_A, Sequence: 3 }]),
    });
    const run = runGate(drifted);
    assert.equal(run.status, 1);
    assert.match(run.stderr, /extra=1 missing=1/);
});

test('a directory the manifest does not classify as loom is not checked', () => {
    const root = fixture({ dirs: { people: { entity: ENTITY, records: [{ ID: ID_A }] } }, seed: '' });
    const ownership = JSON.parse(fs.readFileSync(path.join(root, 'data/ownership.json'), 'utf8'));
    ownership.directories.people.classification = 'frozen';
    fs.writeFileSync(path.join(root, 'data/ownership.json'), JSON.stringify(ownership));

    const run = runGate(root);
    assert.equal(run.status, 0, run.stderr);
    assert.match(run.stdout, /0 loom directories/);
});
