// SQL emitter: converts the JSON packs into SQL Server seed scripts (out/sql/*.sql).
// Usage: node emit-sql.mjs [--out out]   (run build.mjs first)
//
// The JSON-pack → SQL-table MAPPING, deterministic uuidv5 IDs, PREAMBLE (polymorphic refs),
// INSTALL_ORDER (the pack pyramid), and per-table INSERT generation now live in the shared
// ../engine/seed-mapping.mjs so this emitter and the data-migration emitter can never drift.
// This file owns only the out/sql/ output concern.
//
// ⚠ TABLE/COLUMN NAMES ARE ASSUMED SHAPES (see seed-mapping.mjs) — proven loadable. Never emit
// __mj_* audit columns (CodeGen owns those).

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { packSqlLines } from '../engine/seed-render.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const args = Object.fromEntries(process.argv.slice(2).map((a, i, all) => (a.startsWith('--') ? [a.slice(2), all[i + 1]] : null)).filter(Boolean));
const ROOT = join(HERE, '..');
const OUT = join(ROOT, args.out ?? 'out');
const load = (pack, table) => JSON.parse(readFileSync(join(OUT, 'packs', pack, `${table}.json`), 'utf8'));
const run = JSON.parse(readFileSync(join(OUT, 'run.json'), 'utf8'));
// The MAPPING is the PROJECT's, not the engine's — loaded by name so this command knows no domain.
const { MAPPING, INSTALL_ORDER, PREAMBLE, POSTAMBLE } = await import(`../projects/${run.project}/seed-mapping.mjs`);

mkdirSync(join(OUT, 'sql'), { recursive: true });
const summary = [];
let packIndex = 0;
for (const pack of INSTALL_ORDER) {
  packIndex++;
  const lines = [
    `-- MoreCheese demo seed — pack: ${pack} (install order ${packIndex})`,
    `-- Generated by datagen/cli/emit-sql.mjs · seed ${run.seed} · release ${run.releaseDate} · ruleset v${run.ruleset}`,
    `-- Deterministic: same seed + release regenerates this file byte-identically.`,
    `-- ⚠ ASSUMED table/column names pending schema reconciliation. No __mj_* columns (CodeGen owns them).`,
    '',
    ...(PREAMBLE[pack] ?? []),
    ...(PREAMBLE[pack] ? [''] : []),
  ];
  const { lines: bodyLines, summary: packSummary } = packSqlLines(MAPPING, pack, load);
  lines.push(...bodyLines, ...(POSTAMBLE[pack] ?? []));
  for (const s of packSummary) summary.push({ pack, ...s });
  writeFileSync(join(OUT, 'sql', `${String(packIndex).padStart(2, '0')}_${pack}.sql`), lines.join('\n'));
}
writeFileSync(join(OUT, 'sql', '_install-order.txt'),
  'Install packs in file order (the pack dependency pyramid — common first, always):\n' +
  INSTALL_ORDER.map((p, i) => `${String(i + 1).padStart(2, '0')}_${p}.sql`).join('\n') + '\n');

for (const s of summary) console.log(`${s.pack.padEnd(11)} ${s.table.padEnd(46)} ${String(s.rows).padStart(6)} rows`);
console.log(`sql → ${join(OUT, 'sql')}`);
